import deviltea from '@deviltea/eslint-config'
import pikacss from '@pikacss/eslint-config'

export default await deviltea(
	{
		markdown: {
			overrides: {
				'style/indent': ['error', 2],
			},
		},
		ignores: [
			'./.github/**/*',
			// Playground templates are standalone starters served into the
			// WebContainer; they keep their own upstream code style.
			'./playground/src/templates/**/*',
			'./playground/public/**/*',
			// Agent-facing instruction sources: skills, subagent definitions, and the
			// `.agents/skills/*` symlinks that mirror `.claude/skills/*` for other tools.
			'./.claude/**/*',
			'./.agents/**/*',
			'.planning/**/*',
			'./docs/.examples/**/*',
			// zh-TW mirrors of the example fixtures (comment-only translations,
			// validated by the docs example tests + maintain-i18n lint)
			'./docs/zh-tw/.examples/**/*',
			'./docs/**/*.md',
			'./skills/**/*.md',
			// Ignore the generated files
			'packages/core/src/generated/**',
			// Generated by the playground dev server (gitignored, absent in CI)
			'playground/src/vfs.d.ts',
		],
	},
	pikacss(),
	// This focused test verifies that diagnostics preserve non-Error thrown values.
	{
		files: ['packages/core/src/plugin.test.ts'],
		linterOptions: {
			reportUnusedDisableDirectives: 'off',
		},
		rules: {
			'no-throw-literal': 'off',
		},
	},
	// Console access is isolated to the official Node integration host adapter.
	{
		files: ['packages/integration/src/log.ts'],
		linterOptions: {
			reportUnusedDisableDirectives: 'off',
		},
		rules: {
			'no-console': 'off',
		},
	},
)
