const ATOMIC_STYLE_NAME_PLACEHOLDER = '{a}'
const ATOMIC_STYLE_NAME_PLACEHOLDER_RE_GLOBAL = /\{a\}/g
const DEFAULT_SELECTOR_PLACEHOLDER = '{s}'
const DEFAULT_SELECTOR_PLACEHOLDER_RE_GLOBAL = /\{s\}/g

export {
  ATOMIC_STYLE_NAME_PLACEHOLDER,
  ATOMIC_STYLE_NAME_PLACEHOLDER_RE_GLOBAL,
  DEFAULT_SELECTOR_PLACEHOLDER,
  DEFAULT_SELECTOR_PLACEHOLDER_RE_GLOBAL,
}
