import { isAbsolute, resolve } from 'node:path'
import { writeFile } from 'fs/promises'
import type { Plugin as VitePlugin } from 'vite'
import { transformWithEsbuild } from 'vite'
import { normalizePath } from 'vite'
import { resolveModule } from 'local-pkg'
import type { StyoPluginOptions } from './shared/types'
import { DevPlugin } from './dev'
import { BuildPlugin } from './build'
import { createCtx } from './shared'

function StyoPlugin (options: Omit<StyoPluginOptions, 'transformTsToJs'> = {}): VitePlugin[] {
  const ctx = createCtx({
    ...options,
    transformTsToJs: async (tsCode) => (await transformWithEsbuild(tsCode, 'temp.ts')).code,
  })

  const plugins: VitePlugin[] = [
    ...DevPlugin(ctx),
    ...BuildPlugin(ctx),
  ]

  if (ctx.dts) {
    plugins.unshift({
      name: 'styocss:dev:dts',
      async configResolved (config) {
        if (ctx.dts === false)
          return

        const { root } = config

        const normalizedDts = normalizePath(ctx.dts)
        const dtsPath = isAbsolute(normalizedDts)
          ? normalizedDts
          : resolve(root, normalizedDts)

        const { nameOfStyleFn } = ctx
        const nestedWithTemplates = [...ctx.styo.nestedWithTemplateSet].map((n) => `'${n}'`)
        const selectorTemplates = [...ctx.styo.selectorTemplateSet].map((n) => `'${n}'`)
        const macroUtilityNamesOrTemplates = [...ctx.styo.registeredMacroStyoRuleMap]
          .map(([key, val]) => {
            if ('template' in val)
              return `'${val.template}'`

            return `'${key}'`
          })

        const hasVue = !!resolveModule('vue', { paths: [root] })
        const dtsContent = [
          '// Auto-generated by @styocss/vite-plugin-styocss',
          'import type { StyoInstance } from \'@styocss/vite-plugin-styocss\'',
          '',
          'type _StyleFn = StyoInstance<',
          `  ${nestedWithTemplates.length > 0 ? nestedWithTemplates.join(' | ') : 'never'},`,
          `  ${selectorTemplates.length > 0 ? selectorTemplates.join(' | ') : 'never'},`,
          `  ${macroUtilityNamesOrTemplates.length > 0 ? macroUtilityNamesOrTemplates.join(' | ') : 'never'},`,
          '>[\'style\']',
          '',
          ...ctx.autoJoin
            ? [
                'type StyleFn = (...params: Parameters<_StyleFn>) => string',
              ]
            : [
                'type StyleFn = _StyleFn',
              ],
          '',
          'declare global {',
          `  const ${nameOfStyleFn}: StyleFn`,
          '}',
          ...hasVue
            ? [
                '',
                'declare module \'vue\' {',
                '  interface ComponentCustomProperties {',
            `    ${nameOfStyleFn}: StyleFn`,
            '  }',
            '}',
              ]
            : [],
        ].join('\n')
        await writeFile(dtsPath, dtsContent)
      },
    })
  }

  return plugins
}

export type { StyoInstance } from '@styocss/core'

export default StyoPlugin
