/* eslint-disable no-template-curly-in-string */
import { mkdir, mkdtemp, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { log } from '@pikacss/core'
import { dirname, join } from 'pathe'

import { afterEach, describe, expect, it, vi } from 'vitest'
import { createDeferred } from '../../_shared/vitest'
import { PikaTransformError } from './compiler/errors'
import { createCtx } from './ctx'

const WORKSPACE_CWD = process.cwd()
const CORE_INDEX_SPECIFIER = new URL('../../core/src/index.ts', import.meta.url).href

const createdDirs: string[] = []

async function createTempDir() {
	const dir = await mkdtemp(join(tmpdir(), 'pikacss-integration-'))
	createdDirs.push(dir)
	return dir
}

function createOptions(overrides?: Partial<Parameters<typeof createCtx>[0]>) {
	return {
		cwd: '/tmp/pikacss-integration',
		currentPackageName: '@pikacss/core',
		scan: {
			include: ['src/**/*.ts'],
			exclude: [],
		},
		configOrPath: {},
		fnName: 'pika',
		transformedFormat: 'string' as const,
		tsCodegen: 'generated/pika.gen.ts' as const,
		autoCreateConfig: false,
		...overrides,
	}
}

async function withProcessCwd<T>(cwd: string, run: () => Promise<T>) {
	const previousCwd = process.cwd()
	process.chdir(cwd)

	try {
		return await run()
	}
	finally {
		process.chdir(previousCwd)
	}
}

afterEach(async () => {
	vi.restoreAllMocks()
	vi.doUnmock('@pikacss/core')
	vi.resetModules()
	log.setWarnFn(console.warn.bind(console))
	log.setErrorFn(console.error.bind(console))

	while (createdDirs.length > 0) {
		await rm(createdDirs.pop()!, { recursive: true, force: true })
	}
	process.chdir(WORKSPACE_CWD)
})

describe('createCtx', () => {
	it('sets up an inline engine, transforms style calls, and writes generated assets', async () => {
		const cwd = await createTempDir()
		const existingPlugin = { name: 'existing-plugin' }
		const inlineConfig = {
			preflights: [
				{ body: { color: 'red' } },
			],
			plugins: [existingPlugin],
		}
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: inlineConfig,
		}))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		inlineConfig.preflights = []

		expect(ctx.resolvedConfig?.preflights)
			.toHaveLength(1)
		expect(ctx.resolvedConfig?.plugins?.map(plugin => plugin.name))
			.toEqual(['@pikacss/integration:dev', 'existing-plugin'])
		expect(ctx.transformFilter.exclude)
			.toEqual([
				'.pikacss/**',
				'generated/pika.gen.ts',
			])

		const transformed = await ctx.transform([
			'const a = pika({ color: \'red\' })',
			'const b = pika.str({ color: \'blue\' })',
			'const c = pikap.arr({ color: \'green\' })',
		].join('\n'), 'src/demo.ts')

		expect(transformed?.code.includes('pika('))
			.toBe(false)
		expect(transformed?.code.includes('pikap.arr('))
			.toBe(false)
		expect(transformed?.code.includes('['))
			.toBe(true)
		expect(ctx.usages.get(join(cwd, 'src/demo.ts')))
			.toHaveLength(3)
		expect(ctx.previewUsages.get(join(cwd, 'src/demo.ts')))
			.toHaveLength(1)
		expect(ctx.previewUsages.get(join(cwd, 'src/demo.ts'))![0]!.params)
			.toEqual([{ color: 'green' }])
		expect(onStyleUpdated)
			.toHaveBeenCalled()
		expect(onTsUpdated)
			.toHaveBeenCalled()

		const cssContent = await ctx.getCssCodegenContent()
		const tsContent = await ctx.getTsCodegenContent()

		expect(cssContent)
			.toContain('/* Auto-generated by @pikacss/core */')
		expect(cssContent)
			.toContain('color: red;')
		expect(tsContent)
			.toContain('declare global {')
		expect(tsContent)
			.toContain('const pika: StyleFn')

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toBe(cssContent)
		expect(await readFile(join(cwd, 'generated/pika.gen.ts'), 'utf8'))
			.toBe(tsContent)
	})

	it('returns null when transform is called before setup initializes the engine', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		expect(await ctx.transform('const value = pika({ color: \'red\' })', 'src/before-setup.ts'))
			.toBeNull()
	})

	it('exposes path getters, updates cwd, and throws when engine is accessed before setup', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		await mkdir(join(nextCwd, 'node_modules/vue'), { recursive: true })
		await writeFile(join(nextCwd, 'node_modules/vue/package.json'), '{"name":"vue","version":"0.0.0"}')
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: '/tmp/pikacss-fixed.ts',
		}))

		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
		// The runtime CSS path is invocation-owned internal state under the
		// current cwd; only its root follows `cwd`, never user configuration.
		expect(ctx.cssCodegenFilepath.startsWith(join(cwd, '.pikacss/runs/')))
			.toBe(true)
		expect(ctx.cssCodegenFilepath.endsWith('/pika.css'))
			.toBe(true)
		expect(ctx.tsCodegenFilepath)
			.toBe('/tmp/pikacss-fixed.ts')
		expect(ctx.hasVue)
			.toBe(false)

		ctx.cwd = nextCwd

		expect(ctx.cwd)
			.toBe(nextCwd)
		expect(ctx.cssCodegenFilepath.startsWith(join(nextCwd, '.pikacss/runs/')))
			.toBe(true)
		expect(ctx.hasVue)
			.toBe(true)
	})

	it('auto-creates and loads a config scaffold when no config file exists', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			currentPackageName: CORE_INDEX_SPECIFIER,
			configOrPath: null,
			autoCreateConfig: true,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		const configPath = join(cwd, 'pika.config.js')
		const content = await readFile(configPath, 'utf8')

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		expect(ctx.resolvedConfigContent)
			.toContain('defineEngineConfig')
		expect(ctx.resolvedConfig?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
		expect(content)
			.toContain('/// <reference path="./generated/pika.gen.ts" />')
		expect(content)
			.toContain(`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`)
	})

	it('auto-creates a scaffold without a ts reference when TypeScript codegen is disabled', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			currentPackageName: CORE_INDEX_SPECIFIER,
			configOrPath: null,
			autoCreateConfig: true,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		const content = await readFile(join(cwd, 'pika.config.js'), 'utf8')

		expect(content.includes('/// <reference path='))
			.toBe(false)
	})

	it('discovers an existing config file from the scan pattern when no explicit path is provided', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pikacss.config.ts'), [
			`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`,
			'',
			'export default defineEngineConfig({',
			'  preflights: [{ body: { color: \'orange\' } }],',
			'})',
		].join('\n'))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(join(cwd, 'pikacss.config.ts'))
		expect(ctx.resolvedConfigContent)
			.toContain('orange')
		expect(await ctx.getCssCodegenContent())
			.toContain('color: orange;')
	})

	it('deterministically prefers pika over pikacss and warns about the ignored file when multiple match', async () => {
		const cwd = await createTempDir()
		const preferredPath = join(cwd, 'pika.config.ts')
		const ignoredPath = join(cwd, 'pikacss.config.ts')
		for (const candidatePath of [ignoredPath, preferredPath]) {
			await writeFile(candidatePath, 'export default {}\n')
		}

		const warn = vi.fn()
		log.setWarnFn(warn)

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		// Deterministic: `pika` wins over `pikacss` regardless of filesystem order.
		expect(ctx.resolvedConfigPath)
			.toBe(preferredPath)
		const warnings = warn.mock.calls.map(call => call.join(' '))
			.join('\n')
		expect(warnings)
			.toContain('Multiple config files found')
		expect(warnings)
			.toContain(`Using "${preferredPath}"`)
		expect(warnings)
			.toContain(`"${ignoredPath}"`)
	})

	it('deterministically prefers the TS config variant over the JS one', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.js'), 'export default {}\n')
		await writeFile(join(cwd, 'pika.config.ts'), 'export default {}\n')
		log.setWarnFn(vi.fn())

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(join(cwd, 'pika.config.ts'))
	})

	it('does not discover a config file nested in a subdirectory (root-only discovery)', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'fixtures'), { recursive: true })
		await writeFile(join(cwd, 'fixtures/pika.config.ts'), 'export default {}\n')
		log.setWarnFn(vi.fn())

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBeNull()
	})

	it('resolves null when no function call matches and rejects when argument evaluation fails', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		expect(await ctx.transform('const plain = 1', 'src/plain.ts'))
			.toBeNull()

		const valid = await ctx.transform('const value = pika({ color: \'red\' })', 'src/broken.ts')
		expect(valid)
			.toBeDefined()
		expect(ctx.usages.has(join(cwd, 'src/broken.ts')))
			.toBe(true)
		expect(ctx.previewUsages.has(join(cwd, 'src/broken.ts')))
			.toBe(false)

		await expect(ctx.transform('const broken = pika(foo())', 'src/broken.ts'))
			.rejects.toThrow(PikaTransformError)
		// The previously committed usages stay intact (last-good retention).
		expect(ctx.usages.get(join(cwd, 'src/broken.ts')))
			.toHaveLength(1)
		expect(ctx.previewUsages.has(join(cwd, 'src/broken.ts')))
			.toBe(false)
	})

	it('triggers regeneration when the last style call is removed from a file', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)

		await ctx.transform('const value = pika({ color: \'red\' })', 'src/removed.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		await ctx.transform('const value = 1', 'src/removed.ts')
		expect(ctx.usages.has(join(cwd, 'src/removed.ts')))
			.toBe(false)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)
	})

	it('skips update triggers when a re-transform yields identical usages', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		await ctx.transform('// rev 1\nconst a = pika({ color: \'red\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)

		// Different code (comment edit) but identical pika() usages: no triggers.
		await ctx.transform('// rev 2\nconst a = pika({ color: \'red\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)
		expect(ctx.usages.get(join(cwd, 'src/resave.ts')))
			.toHaveLength(1)

		// Changed usages still fire.
		await ctx.transform('// rev 3\nconst a = pika({ color: \'blue\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(2)

		// Switching to a preview call with identical params fires: the preview
		// subset changed even though the usage records are the same.
		await ctx.transform('// rev 4\nconst a = pikap({ color: \'blue\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(3)
		expect(ctx.previewUsages.get(join(cwd, 'src/resave.ts')))
			.toHaveLength(1)

		// A different number of calls fires (length short-circuit in the compare).
		await ctx.transform('// rev 5\nconst a = pikap({ color: \'blue\' })\nconst b = pika({ margin: \'1px\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(4)
	})

	it('reuses the memoized transform result for identical inputs and recomputes when they change', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const useSpy = vi.spyOn(ctx.engine, 'use')

		const code = 'const a = pika({ color: \'red\' })'
		const first = await ctx.transform(code, 'src/memo.ts')
		expect(useSpy)
			.toHaveBeenCalledTimes(1)

		// Same (id, code): the engine work happens once and the cached
		// replacements are reused (the result object itself is rebuilt).
		const second = await ctx.transform(code, 'src/memo.ts')
		expect(useSpy)
			.toHaveBeenCalledTimes(1)
		expect(second?.code)
			.toBe(first?.code)

		// Different code recomputes.
		await ctx.transform('const a = pika({ color: \'blue\' })', 'src/memo.ts')
		expect(useSpy)
			.toHaveBeenCalledTimes(2)

		// setup() swaps the engine and clears the memo: identical code recomputes.
		await ctx.setup()
		const useSpyAfterSetup = vi.spyOn(ctx.engine, 'use')
		await ctx.transform(code, 'src/memo.ts')
		expect(useSpyAfterSetup)
			.toHaveBeenCalledTimes(1)
	})

	it('restores externally dropped usages when a memoized identical file is re-transformed', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const code = [
			'const a = pika({ color: \'red\' })',
			'const b = pikap({ color: \'green\' })',
		].join('\n')
		await ctx.transform(code, 'src/deleted.ts')
		expect(ctx.usages.get(join(cwd, 'src/deleted.ts')))
			.toHaveLength(2)

		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		// Simulate the bundler reporting the file as deleted (watchChange path).
		ctx.usages.delete(join(cwd, 'src/deleted.ts'))
		ctx.previewUsages.delete(join(cwd, 'src/deleted.ts'))

		await ctx.transform(code, 'src/deleted.ts')
		expect(ctx.usages.get(join(cwd, 'src/deleted.ts')))
			.toHaveLength(2)
		expect(ctx.previewUsages.get(join(cwd, 'src/deleted.ts')))
			.toHaveLength(1)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)
	})

	it('rejects the whole module and commits nothing when a sibling call fails to evaluate', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// Module transforms are atomic: one failing call rejects the module and
		// the valid sibling call is not committed either.
		await expect(ctx.transform([
			'const ok = pika({ color: \'red\' })',
			'const broken = pika({ color: localVariable })',
		].join('\n'), 'src/partial.ts'))
			.rejects.toThrow(PikaTransformError)
		expect(ctx.usages.has(join(cwd, 'src/partial.ts')))
			.toBe(false)
		expect(ctx.previewUsages.has(join(cwd, 'src/partial.ts')))
			.toBe(false)
	})

	it('handles bracket-call variants, nested template expressions, and comments while transforming', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			transformedFormat: 'array',
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'const a = pika[\'str\']({ color: \'red\' /* inline comment */ })',
			'const b = pika[`arr`]({ content: `calc(${`1`})` })',
			'const c = pikap({ color: \'blue\' // trailing comment\n})',
		].join('\n'), 'src/complex.ts')

		expect(transformed?.code)
			.toContain('[')
		expect(transformed?.code.includes('pika['))
			.toBe(false)
		expect(ctx.usages.get(join(cwd, 'src/complex.ts')))
			.toHaveLength(3)
		expect(ctx.previewUsages.get(join(cwd, 'src/complex.ts')))
			.toHaveLength(1)
	})

	it('transforms pika() calls inside Vue SFC template attributes', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.{ts,vue}'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<script setup lang="ts">',
			'const fromScript = pika({ color: \'gold\' })',
			'</script>',
			'',
			'<template>',
			'\t<!-- <div :class="pika({ color: \'red\' })"> -->',
			'\t<div :class="pika({ height: \'100vh\', display: \'flex\' })">',
			'\t\t<span :class="pika({ fontSize: \'0.875rem\' })">text</span>',
			'\t</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		expect(transformed?.code.includes('pika({ color: \'gold\' })'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ height:'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ fontSize:'))
			.toBe(false)
		// The commented-out call must survive untouched.
		expect(transformed?.code)
			.toContain('<!-- <div :class="pika({ color: \'red\' })"> -->')
		// Replacements must stay single-quoted inside double-quoted attributes.
		expect(transformed?.code)
			.toMatch(/:class="'[^"]*'"/)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(3)
	})

	it('escapes line terminators when serializing unresolved string style items', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// `new Function` evaluation turns the source `\n` escape into a real LF,
		// which the engine echoes back verbatim for unresolved string items.
		const transformed = await ctx.transform('const value = pika(\'a\\nb\')', 'src/newline.ts')

		expect(transformed?.code)
			.toContain('\'a\\nb\'')
		// The emitted literal must not contain a raw line terminator.
		expect(transformed?.code)
			.not.toContain('\n')
		// eslint-disable-next-line no-new-func
		expect(() => new Function(transformed!.code))
			.not.toThrow()
	})

	it('does not rewrite pika lookalikes inside script-block literals and comments of markup sources', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<script setup lang="ts">',
			'const tip = "use pika(\'bg:red\') here"',
			'// pika({ color: \'red\' })',
			'/* pika({ color: \'green\' }) */',
			'const real = pika({ color: \'gold\' })',
			'</script>',
			'',
			'<template>',
			'\t<div :class="pika({ color: \'blue\' })">real</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		// Lookalikes inside script-block literals and JS comments survive untouched.
		expect(transformed?.code)
			.toContain('const tip = "use pika(\'bg:red\') here"')
		expect(transformed?.code)
			.toContain('// pika({ color: \'red\' })')
		expect(transformed?.code)
			.toContain('/* pika({ color: \'green\' }) */')
		// Real calls in the script block and the template attribute are rewritten.
		expect(transformed?.code.includes('pika({ color: \'gold\' })'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ color: \'blue\' })'))
			.toBe(false)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(2)
	})

	it('emits double-quoted literals inside single-quoted markup attributes', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<template>',
			'\t<div :class=\'pika({ color: "red" })\'>',
			'\t\t<span :class="pika({ color: \'blue\' })">text</span>',
			'\t</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		// Single-quoted attribute stays intact: the literal uses double quotes.
		expect(transformed?.code)
			.toMatch(/:class='"[^']*"'/)
		// Double-quoted attribute keeps the existing single-quoted output.
		expect(transformed?.code)
			.toMatch(/:class="'[^"]*'"/)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(2)
	})

	it('keeps single-quoted output for a double-quoted attribute containing a string comparison', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		// Regression: the `== 'dark'` comparison used to make the quote detector
		// pick `"`, emitting a double-quoted literal into the double-quoted
		// attribute and breaking it. The literal must stay single-quoted.
		const transformed = await ctx.transform([
			'<template>',
			'\t<div :class="mode == \'dark\' ? pika({ color: \'white\' }) : \'\'">x</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		expect(transformed?.code)
			.toMatch(/\?\s*'[^"]*'\s*:/)
		// The double-quoted :class attribute is not closed early by the literal.
		expect(transformed?.code)
			.not.toMatch(/:class="[^"]*"[^"]*"/)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(1)
	})

	it('buffers style and ts updates until all concurrent transforms finish', async () => {
		const firstUse = createDeferred<string[]>()
		const secondUse = createDeferred<string[]>()
		let useCallCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				const devPlugin = config.plugins?.find((plugin: any) => plugin.name === '@pikacss/integration:dev')
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					use: vi.fn(async () => {
						devPlugin?.atomicStyleAdded?.()
						devPlugin?.autocompleteConfigUpdated?.()

						useCallCount++
						return useCallCount === 1 ? firstUse.promise : secondUse.promise
					}),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const options = createOptions()
		const ctx = createMockedCtx(options)

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		const firstTransform = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		const secondTransform = ctx.transform('const b = pika({ color: \'blue\' })', 'src/b.ts')

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		firstUse.resolve(['pk-a'])
		await firstTransform

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		secondUse.resolve(['pk-b'])
		await secondTransform

		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)
		expect(ctx.usages.get(join(options.cwd, 'src/a.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.usages.get(join(options.cwd, 'src/b.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-b'])
	})

	it('waits for the remaining transform when a concurrent transform fails early', async () => {
		const firstUse = createDeferred<string[]>()

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				const devPlugin = config.plugins?.find((plugin: any) => plugin.name === '@pikacss/integration:dev')
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					use: vi.fn(async () => {
						devPlugin?.atomicStyleAdded?.()
						devPlugin?.autocompleteConfigUpdated?.()
						return firstUse.promise
					}),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const options = createOptions()
		const ctx = createMockedCtx(options)

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		const firstTransform = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		const failedTransform = ctx.transform('const broken = pika(foo())', 'src/b.ts')

		// `vi.resetModules()` gives the re-imported ctx its own error class
		// identity, so match on the message instead of the constructor.
		await expect(failedTransform)
			.rejects.toThrow('Failed to statically evaluate pika() argument')

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		firstUse.resolve(['pk-a'])
		await firstTransform

		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)
		expect(ctx.usages.get(join(options.cwd, 'src/a.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.usages.has(join(options.cwd, 'src/b.ts')))
			.toBe(false)
	})

	it('drains in-flight transforms before setup clears state and swaps the engine', async () => {
		const firstUse = createDeferred<string[]>()
		let engineCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				engineCount++
				const engineIndex = engineCount
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					use: vi.fn(async () => engineIndex === 1 ? firstUse.promise : ['pk-new']),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const options = createOptions()
		const ctx = createMockedCtx(options)

		await ctx.setup()

		// Suspended at the first engine's `use()` call.
		const inFlight = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')

		let setupDone = false
		const setupPromise = ctx.setup()
			.then(() => {
				setupDone = true
			})

		// Setup must stay parked on the drain while the transform is in flight.
		await new Promise(resolve => setTimeout(resolve, 10))
		expect(setupDone)
			.toBe(false)

		firstUse.resolve(['pk-old'])
		await inFlight
		await setupPromise

		// The late transform completed before setup cleared state, so its
		// old-engine usages were not written into the new engine's session.
		expect(ctx.usages.size)
			.toBe(0)

		// A re-transform after setup records usages resolved by the new engine.
		await ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		expect(ctx.usages.get(join(options.cwd, 'src/a.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-new'])
	})

	it('exposes idle state via isIdle and resolves waitForIdle once in-flight transforms settle', async () => {
		const firstUse = createDeferred<string[]>()
		let useCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => ({
				config,
				store: {
					atomicStyleIds: new Map(),
				},
				use: vi.fn(async () => {
					useCount++
					return useCount === 1 ? firstUse.promise : ['pk-a']
				}),
				renderLayerOrderDeclaration: vi.fn(() => ''),
				renderPreflights: vi.fn(async () => ''),
				renderAtomicStyles: vi.fn(async () => ''),
			}))

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions())

		await ctx.setup()

		// Idle context: the sync flag is set and waitForIdle resolves immediately.
		expect(ctx.isIdle)
			.toBe(true)
		await ctx.waitForIdle()

		// Suspended at the engine's `use()` call: the context reports busy and
		// waitForIdle stays pending until the transform settles.
		const inFlight = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		await new Promise(resolve => setTimeout(resolve, 0))
		expect(ctx.isIdle)
			.toBe(false)

		let idleResolved = false
		const idlePromise = ctx.waitForIdle()
			.then(() => {
				idleResolved = true
			})
		await new Promise(resolve => setTimeout(resolve, 10))
		expect(idleResolved)
			.toBe(false)

		firstUse.resolve(['pk-a'])
		await inFlight
		await idlePromise
		expect(idleResolved)
			.toBe(true)
		expect(ctx.isIdle)
			.toBe(true)
	})

	it('rejects unparsable sources and ignores pika lookalikes inside comments and strings', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// Lookalikes inside comments and string literals never match under AST
		// semantics: no macro call is collected and the module resolves null.
		expect(await ctx.transform([
			'// pika({ color: \'red\' })',
			'/* pika({ color: \'green\' }) */',
			'const tip = "use pika(\'bg:red\') here"',
		].join('\n'), 'src/lookalikes.ts'))
			.toBeNull()
		expect(ctx.usages.has(join(cwd, 'src/lookalikes.ts')))
			.toBe(false)

		// Genuinely malformed sources are parse hard-errors.
		await expect(ctx.transform('const a = pika({ color: `red ${`', 'src/malformed-template.ts'))
			.rejects.toThrow(PikaTransformError)
		await expect(ctx.transform('const b = pika({ color: \'red\' /*', 'src/unclosed-comment.ts'))
			.rejects.toThrow(PikaTransformError)
		await expect(ctx.transform('const c = pika({', 'src/unterminated-call.ts'))
			.rejects.toThrow(PikaTransformError)
	})

	it('skips TypeScript generation when it is disabled and performs full CSS scanning', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src', 'demo.ts'), 'export const value = pika({ color: \'red\' })')
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('/* Auto-generated by @pikacss/core */')
	})

	it('evaluates transform targets against the current cwd and always rejects codegen outputs', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['**/*.{ts,css}'],
				exclude: ['node_modules/**', 'dist/**', join(nextCwd, 'abs-excluded/**')],
			},
		}))

		// Relative excludes and ids must follow the updated cwd, not the one the
		// context was created with.
		ctx.cwd = nextCwd

		expect(ctx.isTransformTarget(join(nextCwd, 'src/demo.ts')))
			.toBe(true)
		// Relative ids resolve against the current cwd.
		expect(ctx.isTransformTarget('src/demo.ts'))
			.toBe(true)
		// Query/hash suffixes are ignored.
		expect(ctx.isTransformTarget(`${join(nextCwd, 'src/demo.ts')}?raw`))
			.toBe(true)
		// cwd-relative excludes are resolved against the current cwd.
		expect(ctx.isTransformTarget(join(nextCwd, 'node_modules/pkg/index.ts')))
			.toBe(false)
		expect(ctx.isTransformTarget(join(nextCwd, 'dist/out.ts')))
			.toBe(false)
		// Codegen outputs are always rejected, even when they match the include globs.
		expect(ctx.isTransformTarget(join(nextCwd, 'generated/pika.gen.ts')))
			.toBe(false)
		// Internal runtime state (including the invocation-owned CSS) is always
		// rejected via the default `.pikacss/**` exclude.
		expect(ctx.isTransformTarget(ctx.cssCodegenFilepath))
			.toBe(false)
		expect(ctx.isTransformTarget(join(nextCwd, '.pikacss/internal-note.css')))
			.toBe(false)
		// Absolute exclude patterns match against the absolute id.
		expect(ctx.isTransformTarget(join(nextCwd, 'abs-excluded/skip.ts')))
			.toBe(false)
		// Non-included files are rejected.
		expect(ctx.isTransformTarget(join(nextCwd, 'README.md')))
			.toBe(false)
	})

	it('skips the codegen output files during full CSS scanning even when they match scan.include', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/demo.ts'), 'export const value = pika({ color: \'red\' })')
		// A stale codegen output that matches the include glob must not be scanned.
		const tsCodegenFilepath = join(cwd, 'src/pika.gen.ts')
		await writeFile(tsCodegenFilepath, 'export const leaked = pika({ color: \'blue\' })')

		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: 'src/pika.gen.ts',
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(ctx.usages.has(tsCodegenFilepath))
			.toBe(false)
		const css = await readFile(ctx.cssCodegenFilepath, 'utf8')
		expect(css)
			.toContain('color: red')
		expect(css)
			.not.toContain('color: blue')
	})

	it('prunes variables and keyframes of styles whose usages were removed', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: {
				variables: {
					definitions: {
						'--main-color': 'red',
					},
				},
				keyframes: {
					definitions: [
						['spin', { from: { opacity: '0' }, to: { opacity: '1' } }],
					],
				},
			},
		}))

		await ctx.setup()

		await ctx.transform('const a = pika({ color: \'var(--main-color)\', animationName: \'spin\' })', 'src/anim.ts')
		const withUsage = await ctx.getCssCodegenContent()
		expect(withUsage)
			.toContain('--main-color')
		expect(withUsage)
			.toContain('@keyframes spin')

		// Deleting the usage (as watchChange/transform would) must drop the
		// variable and keyframes from the regenerated CSS despite the
		// append-only engine store.
		await ctx.transform('const a = 1', 'src/anim.ts')
		const withoutUsage = await ctx.getCssCodegenContent()
		expect(withoutUsage)
			.not.toContain('--main-color')
		expect(withoutUsage)
			.not.toContain('@keyframes spin')
	})

	it('honors explicit config paths and leaves tsCodegen excludes empty when disabled', async () => {
		const cwd = await createTempDir()
		const configPath = join(cwd, 'configs/pikacss.config.ts')
		await mkdir(join(cwd, 'configs'), { recursive: true })
		await writeFile(configPath, [
			`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`,
			'',
			'export default defineEngineConfig({',
			'  preflights: [{ body: { color: \'purple\' } }],',
			'})',
		].join('\n'))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: 'configs/pikacss.config.ts',
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		expect(ctx.transformFilter.exclude)
			.toEqual([
				'.pikacss/**',
			])
		expect(await ctx.getCssCodegenContent())
			.toContain('color: purple;')
	})

	it('returns null config data when config lookup is disabled or the path extension is invalid', async () => {
		const cwd = await createTempDir()
		const warn = vi.fn()
		log.setWarnFn(warn)
		const disabledLookup = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
			tsCodegen: false,
		}))
		const invalidExt = createCtx(createOptions({
			cwd,
			configOrPath: 'pika.config.txt',
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			expect(await disabledLookup.loadConfig())
				.toEqual({ config: null, file: null, content: null })
			expect(await invalidExt.loadConfig())
				.toEqual({ config: null, file: null, content: null })
		})

		expect(disabledLookup.resolvedConfigPath)
			.toBeNull()
		expect(invalidExt.resolvedConfigPath)
			.toBeNull()
		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('No PikaCSS config file found')))
			.toBe(true)
	})

	it('sets up a default engine config when no config file is available', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfig)
			.toBeNull()
		expect(ctx.engine.config.plugins?.some(plugin => plugin.name === '@pikacss/integration:dev'))
			.toBe(true)
	})

	it('keeps the config file path and content when the config file throws during evaluation', async () => {
		const cwd = await createTempDir()
		const error = vi.fn()
		log.setErrorFn(error)
		const configPath = join(cwd, 'pika.config.ts')
		const configContent = 'throw new Error("invalid config")'
		await writeFile(configPath, configContent)

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			// The path and content are preserved so integrations can keep
			// watching the config file and reload once the user fixes it.
			expect(await ctx.loadConfig())
				.toEqual({ config: null, file: configPath, content: configContent })
		})

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to evaluate config file: invalid config')))
			.toBe(true)
	})

	it('build mode: rejects setup instead of falling back when the config file fails to evaluate', async () => {
		const cwd = await createTempDir()
		log.setErrorFn(vi.fn())
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, 'throw new Error("invalid config")')

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))
		ctx.configErrorBehavior = 'throw'

		await withProcessCwd(cwd, async () => {
			await expect(ctx.setup())
				.rejects
				.toThrow('invalid config')
		})
		// A failed build setup must not leave a usable engine behind.
		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
	})

	it('build mode: rejects setup when engine creation fails instead of falling back to defaults', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			return {
				...actual,
				createEngine: vi.fn(async () => {
					throw new Error('engine boom')
				}),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		core.log.setErrorFn(vi.fn())
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-build-throw',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			autoCreateConfig: false,
		})
		ctx.configErrorBehavior = 'throw'

		await expect(ctx.setup())
			.rejects
			.toThrow('engine boom')
		// The plugin-only default fallback must not run in build mode.
		expect((core.createEngine as any).mock.calls)
			.toHaveLength(1)
	})

	it('dev mode: retains the last known good engine when a config reload fails, then recovers', async () => {
		const cwd = await createTempDir()
		log.setErrorFn(vi.fn())
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, 'export default {}')

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))
		// Default behavior is 'retain-last-good'; assert it explicitly.
		expect(ctx.configErrorBehavior)
			.toBe('retain-last-good')

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			const goodEngine = ctx.engine

			// Break the config and reload: the engine must be retained untouched.
			await writeFile(configPath, 'throw new Error("broke it")')
			await ctx.setup()
			expect(ctx.engine)
				.toBe(goodEngine)
			expect(ctx.resolvedConfig)
				.toBeNull()

			// Fix the config and reload: the engine is rebuilt (recovery).
			await writeFile(configPath, 'export default {}')
			await ctx.setup()
			expect(ctx.engine)
				.not
				.toBe(goodEngine)
		})
	})

	it('skips writing generated files when the derived content is null', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		vi.spyOn(ctx, 'getCssCodegenContent')
			.mockResolvedValueOnce(null)
		vi.spyOn(ctx, 'getTsCodegenContent')
			.mockResolvedValueOnce(null)

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		await expect(readFile(ctx.cssCodegenFilepath, 'utf8'))
			.rejects
			.toThrow()
		expect(ctx.tsCodegenFilepath)
			.toBe(join(cwd, 'generated/pika.gen.ts'))
	})

	it('returns early when TypeScript codegen is disabled and when css output collapses to only the banner', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await ctx.setup()
		vi.spyOn(ctx.engine, 'renderLayerOrderDeclaration')
			.mockReturnValue('')
		vi.spyOn(ctx.engine, 'renderPreflights')
			.mockResolvedValue('')
		vi.spyOn(ctx.engine, 'renderAtomicStyles')
			.mockResolvedValue('')

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await ctx.getCssCodegenContent())
			.toBe('/* Auto-generated by @pikacss/core */')

		await ctx.writeTsCodegenFile()
	})

	it('retries engine creation with a default plugin-only config when the initial createEngine call fails', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, unknown>) => {
				if (createEngine.mock.calls.length === 1) {
					throw new Error('boom')
				}

				return {
					config,
					use: vi.fn(async () => []),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect((core.createEngine as any).mock.calls)
			.toHaveLength(2)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins)
			.toHaveLength(1)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
	})

	it('logs and clears setupPromise when both engine creation attempts fail', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async () => {
				throw new Error('still broken')
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const error = vi.fn()
		core.log.setErrorFn(error)
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to setup integration context: still broken')))
			.toBe(true)
		expect(ctx.setupPromise)
			.toBeNull()
	})

	it('skips byte-identical runtime CSS rewrites and cleans up when the replacement fails', async () => {
		const cwd = await createTempDir()
		const calls = { writeFile: 0, rename: 0 }
		let failNextRename = false
		let failNextTempWrite = false
		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				writeFile: async (...args: any[]) => {
					calls.writeFile++
					if (failNextTempWrite && typeof args[0] === 'string' && args[0].endsWith('.tmp')) {
						failNextTempWrite = false
						// Leave a partial temp file behind, like an interrupted write.
						await (actual.writeFile as any)(args[0], 'partial')
						throw new Error('ENOSPC: temp write interrupted')
					}
					return (actual.writeFile as any)(...args)
				},
				rename: async (...args: any[]) => {
					calls.rename++
					if (failNextRename) {
						failNextRename = false
						throw new Error('EPERM: rename blocked')
					}
					return (actual.rename as any)(...args)
				},
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))
		await ctx.setup()
		await ctx.transform('export const a = pika({ color: \'red\' })', 'src/a.ts')

		await ctx.writeCssCodegenFile()
		const afterFirstWrite = { ...calls }
		expect(afterFirstWrite.rename)
			.toBe(1)

		// Byte-identical content: the rewrite is a filesystem no-op — no temp
		// file, no replacement, no mtime churn.
		await ctx.writeCssCodegenFile()
		expect(calls)
			.toEqual(afterFirstWrite)

		// A failed replacement removes its unique temp file, propagates the
		// error, and leaves the previous complete stylesheet in place.
		await ctx.transform('export const b = pika({ display: \'flex\' })', 'src/b.ts')
		failNextRename = true
		await expect(ctx.writeCssCodegenFile())
			.rejects
			.toThrow('rename blocked')
		// Temps live in the dedicated .pikacss/tmp directory (outside the
		// watched run directory) and never leave residue behind.
		const listTemps = async () => {
			const runDirTemps = (await readdir(dirname(ctx.cssCodegenFilepath))).filter(name => name.endsWith('.tmp'))
			const tempDirTemps = await readdir(join(cwd, '.pikacss/tmp'))
				.catch(() => [] as string[])
			return [...runDirTemps, ...tempDirTemps]
		}
		expect(await listTemps())
			.toEqual([])
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('color: red')

		// A failure during the temp write itself (partial temp on disk, then
		// an error) is cleaned up the same way: error propagates, no temp
		// residue, and the previous complete stylesheet stays in place.
		failNextTempWrite = true
		await expect(ctx.writeCssCodegenFile())
			.rejects
			.toThrow('temp write interrupted')
		expect(await listTemps())
			.toEqual([])
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('color: red')
	})

	it('swallows mkdir errors and still writes the generated file when the directory already exists', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'generated'), { recursive: true })

		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				mkdir: vi.fn()
					.mockRejectedValue(new Error('EACCES: permission denied')),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))
		// Pre-create the invocation-owned run directory and the temp directory
		// with the real mkdir (imported before the doMock), so only the
		// writer's own mkdir calls fail.
		await mkdir(dirname(ctx.cssCodegenFilepath), { recursive: true })
		await mkdir(join(cwd, '.pikacss/tmp'), { recursive: true })

		await ctx.setup()
		await ctx.writeCssCodegenFile()

		const content = await readFile(ctx.cssCodegenFilepath, 'utf-8')
		expect(content)
			.toContain('Auto-generated')
	})

	it('generates byte-identical CSS across full scans regardless of file creation order', async () => {
		// The two files mint different atomic ids depending on which one the
		// engine resolves first; path-sorted commit order makes it deterministic.
		const files: [string, string][] = [
			['src/a.ts', 'export const a = pika({ color: \'red\' })'],
			['src/z.ts', 'export const z = pika({ color: \'blue\' })'],
		]

		async function generate(order: 'forward' | 'reverse') {
			const cwd = await createTempDir()
			await mkdir(join(cwd, 'src'), { recursive: true })
			const ordered = order === 'forward' ? files : [...files].reverse()
			for (const [file, code] of ordered) {
				await writeFile(join(cwd, file), code)
			}

			const ctx = createCtx(createOptions({ cwd }))
			await withProcessCwd(cwd, async () => {
				await ctx.setup()
				await ctx.fullyCssCodegen()
			})
			return readFile(ctx.cssCodegenFilepath, 'utf8')
		}

		const first = await generate('forward')
		const second = await generate('forward')
		const reversed = await generate('reverse')

		expect(second)
			.toBe(first)
		expect(reversed)
			.toBe(first)
	})

	it('skips Vue SFC sub-requests carrying a vue&type= query', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const result = await ctx.transform(
			'export default { computed: { cls: () => pika({ color: \'red\' }) } }',
			join(cwd, 'src/App.vue?vue&type=script&lang.ts'),
		)
		expect(result)
			.toBeNull()
		expect(ctx.usages.size)
			.toBe(0)
	})

	it('reports scanned-but-not-transformed files until the bundler pass reaches them', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		const file = join(cwd, 'src/dead.ts')
		const code = 'export const a = pika({ color: \'red\' })'
		await writeFile(file, code)
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		await ctx.fullyCssCodegen()
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([file])

		// The bundler pass reaching the file clears it from the report.
		await ctx.transform(code, file)
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([])
	})

	it('drops usages keyed by the normalized path when dropModule receives a raw relative id', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)

		await ctx.transform('const a = pika({ color: \'red\' })', 'src/dropped.ts')
		const file = join(cwd, 'src/dropped.ts')
		expect(ctx.usages.has(file))
			.toBe(true)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		ctx.dropModule('src/dropped.ts')
		expect(ctx.usages.has(file))
			.toBe(false)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)
	})

	it('keeps the last-good usages when a re-transform of a previously good file rejects', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const file = join(cwd, 'src/last-good.ts')

		await ctx.transform('const a = pika({ color: \'red\' })', 'src/last-good.ts')
		const committed = ctx.usages.get(file)
		expect(committed)
			.toHaveLength(1)

		await expect(ctx.transform('const a = pika({ color: broken })', 'src/last-good.ts'))
			.rejects.toThrow(PikaTransformError)
		expect(ctx.usages.get(file))
			.toBe(committed)
	})

	it('serves a cache hit for identical (id, code) without extra engine work', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const useSpy = vi.spyOn(ctx.engine, 'use')

		const code = 'const a = pika({ color: \'red\' })'
		const first = await ctx.transform(code, 'src/cache-hit.ts')
		const callsAfterFirst = useSpy.mock.calls.length

		const second = await ctx.transform(code, 'src/cache-hit.ts')
		expect(useSpy.mock.calls.length)
			.toBe(callsAfterFirst)
		expect(second?.code)
			.toContain('\'pk-')
		expect(second?.code)
			.toBe(first?.code)
	})
})
