/* eslint-disable no-template-curly-in-string */
import { mkdir, mkdtemp, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { log } from '@pikacss/core'
import { dirname, join } from 'pathe'

import { afterEach, describe, expect, it, vi } from 'vitest'
import { createDeferred } from '../../_shared/vitest'
import { PikaTransformError } from './compiler/errors'
import { createCtx } from './ctx'

const WORKSPACE_CWD = process.cwd()
const CONFIG_INDEX_SPECIFIER = new URL('../../config/src/index.ts', import.meta.url).pathname

function projectConfigSource(body: string): string {
	return [
		`import { defineConfig } from ${JSON.stringify(CONFIG_INDEX_SPECIFIER)}`,
		body,
	].join('\n')
}

const createdDirs: string[] = []

async function createTempDir() {
	const dir = await mkdtemp(join(tmpdir(), 'pikacss-integration-'))
	createdDirs.push(dir)
	return dir
}

function createOptions(overrides?: Partial<Parameters<typeof createCtx>[0]>) {
	return {
		cwd: '/tmp/pikacss-integration',
		currentPackageName: '@pikacss/core',
		scan: {
			include: ['src/**/*.ts'],
			exclude: [],
		},
		configOrPath: {},
		fnName: 'pika',
		transformedFormat: 'string' as const,
		tsCodegen: 'generated/pika.gen.ts' as const,
		autoCreateConfig: false,
		...overrides,
	}
}

async function withProcessCwd<T>(cwd: string, run: () => Promise<T>) {
	const previousCwd = process.cwd()
	process.chdir(cwd)

	try {
		return await run()
	}
	finally {
		process.chdir(previousCwd)
	}
}

afterEach(async () => {
	vi.restoreAllMocks()
	vi.doUnmock('@pikacss/core')
	vi.resetModules()
	log.setWarnFn(console.warn.bind(console))
	log.setErrorFn(console.error.bind(console))

	while (createdDirs.length > 0) {
		await rm(createdDirs.pop()!, { recursive: true, force: true })
	}
	process.chdir(WORKSPACE_CWD)
})

describe('createCtx', () => {
	it('sets up an inline engine, transforms style calls, and writes generated assets', async () => {
		const cwd = await createTempDir()
		const existingPlugin = { name: 'existing-plugin' }
		const inlineConfig = {
			preflights: [
				{ body: { color: 'red' } },
			],
			plugins: [existingPlugin],
		}
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: inlineConfig,
		}))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		inlineConfig.preflights = []

		expect(ctx.resolvedConfig?.preflights)
			.toHaveLength(1)
		expect(ctx.resolvedConfig?.plugins?.map(plugin => plugin.name))
			.toEqual(['@pikacss/integration:dev', 'existing-plugin'])
		expect(ctx.transformFilter.exclude)
			.toEqual([
				'.pikacss/**',
				'generated/pika.gen.ts',
			])

		const transformed = await ctx.transform([
			'const a = pika({ color: \'red\' })',
			'const b = pika({ color: \'blue\' })',
			'const c = pika({ color: \'green\' })',
		].join('\n'), 'src/demo.ts')

		expect(transformed?.code.includes('pika('))
			.toBe(false)
		expect(ctx.usages.get(join(cwd, 'src/demo.ts')))
			.toHaveLength(3)
		expect(onStyleUpdated)
			.toHaveBeenCalled()
		// Generated declarations are a projection of the effective project/type
		// configuration: source transforms never fire the typegen hook (#113).
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		const cssContent = await ctx.getCssCodegenContent()
		const tsContent = await ctx.getTsCodegenContent()

		expect(cssContent)
			.toContain('/* Auto-generated by @pikacss/core */')
		expect(cssContent)
			.toContain('color: red;')
		expect(tsContent)
			.toContain('declare global {')
		expect(tsContent)
			.toContain('const pika: __PikaTypegenUnit0.Pika')

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toBe(cssContent)
		expect(await readFile(join(cwd, 'generated/pika.gen.ts'), 'utf8'))
			.toBe(tsContent)
	})

	it('returns null when transform is called before setup initializes the engine', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		expect(await ctx.transform('const value = pika({ color: \'red\' })', 'src/before-setup.ts'))
			.toBeNull()
		ctx.dropModule('src/before-setup.ts')
		expect(await ctx.resolveCssModule('pika.css'))
			.toBe(ctx.cssCodegenFilepath)
		expect(await ctx.resolveCssModule('other.css'))
			.toBeNull()
	})

	it('exposes path getters, updates cwd, and throws when engine is accessed before setup', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		await mkdir(join(nextCwd, 'node_modules/vue'), { recursive: true })
		await writeFile(join(nextCwd, 'node_modules/vue/package.json'), '{"name":"vue","version":"0.0.0"}')
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: '/tmp/pikacss-fixed.ts',
		}))

		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
		// The runtime CSS path is invocation-owned internal state under the
		// current cwd; only its root follows `cwd`, never user configuration.
		expect(ctx.cssCodegenFilepath.startsWith(join(cwd, '.pikacss/runs/')))
			.toBe(true)
		expect(ctx.cssCodegenFilepath.endsWith('/pika.css'))
			.toBe(true)
		expect(ctx.tsCodegenFilepath)
			.toBe('/tmp/pikacss-fixed.ts')
		expect(ctx.hasVue)
			.toBe(false)

		ctx.cwd = nextCwd

		expect(ctx.cwd)
			.toBe(nextCwd)
		expect(ctx.cssCodegenFilepath.startsWith(join(nextCwd, '.pikacss/runs/')))
			.toBe(true)
		expect(ctx.hasVue)
			.toBe(true)
	})

	it('discovers and evaluates a canonical defineConfig project when no explicit path is provided', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({
				engine: { preflights: [{ body: { color: 'orange' } }] },
				scan: { include: ['src/**/*.ts'], exclude: [] },
			})
		`))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(join(cwd, 'pika.config.ts'))
		expect(ctx.resolvedConfigContent)
			.toContain('orange')
		expect(await ctx.getCssCodegenContent())
			.toContain('color: orange;')
	})

	it('exercises the canonical ProjectRuntime compatibility facade end to end', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/a.ts'), `export const cls = styled({ color: 'red' })\n`)
		await writeFile(join(cwd, 'src/plain.ts'), `export const plain = 1\n`)
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({
				fnName: 'styled',
				transformedFormat: 'array',
				cssModule: 'project.css',
				scan: { include: ['src/**/*.ts'], exclude: [] },
				engine: {},
			})
		`))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			tsCodegen: 'generated/project.gen.ts',
		}))

		// Before activation these are compatibility fallbacks; canonical target
		// filtering still knows enough to reject unsupported/generated ids.
		expect(ctx.fnName)
			.toBe('pika')
		expect(ctx.transformedFormat)
			.toBe('string')
		expect(ctx.cwd)
			.toBe(cwd)
		expect(ctx.cssCodegenFilepath)
			.toContain(join(cwd, '.pikacss/runs'))
		expect(ctx.tsCodegenFilepath)
			.toBe(join(cwd, 'generated/project.gen.ts'))
		void ctx.hasVue
		expect(ctx.usages.size)
			.toBe(0)
		expect(ctx.isIdle)
			.toBe(true)
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([])
		await expect(ctx.waitForIdle())
			.resolves.toBeUndefined()
		expect(ctx.isTransformTarget('src/pre-setup.ts'))
			.toBe(true)
		expect(ctx.isTransformTarget('src/pre-setup.css'))
			.toBe(false)
		expect(ctx.isTransformTarget(ctx.tsCodegenFilepath!))
			.toBe(false)
		ctx.dropModule('src/not-yet-known.ts')

		const setup = ctx.setup()
		expect(ctx.setupPromise)
			.toBe(setup)
		await setup
		expect(ctx.setupPromise)
			.toBeNull()
		// Compatibility setter remains part of the H1-era facade; a null write is
		// intentionally inert and locks the getter/setter projection.
		ctx.setupPromise = null

		expect(ctx.fnName)
			.toBe('styled')
		expect(ctx.transformedFormat)
			.toBe('array')
		expect(ctx.resolvedConfig).not.toBeNull()
		expect(ctx.resolvedConfigPath)
			.toBe(join(cwd, 'pika.config.ts'))
		expect(ctx.resolvedConfigContent)
			.toContain('fnName: \'styled\'')
		expect(ctx.engine)
			.toBeDefined()
		expect(ctx.isTransformTarget('src/a.ts'))
			.toBe(true)
		expect(ctx.isTransformTarget('other/a.ts'))
			.toBe(false)

		const loaded = await ctx.loadConfig()
		expect(loaded.file)
			.toBe(join(cwd, 'pika.config.ts'))
		expect(await ctx.resolveCssModule('project.css'))
			.toBe(ctx.cssCodegenFilepath)
		expect(await ctx.resolveCssModule('missing.css'))
			.toBeNull()
		const typegenBeforeUsage = await ctx.getTsCodegenContent()

		const transformed = await ctx.transform(`export const cls = styled({ color: 'red' })`, 'src/a.ts')
		expect(transformed?.code)
			.toContain('[')
		expect(ctx.usages.size)
			.toBe(1)
		// Semantic commit may finish before its generation/entry CSS publication.
		expect(ctx.isIdle)
			.toBe(false)
		await ctx.waitForIdle()
		expect(ctx.isIdle)
			.toBe(true)

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('color: red')
		const typegen = await ctx.getTsCodegenContent()
		expect(typegen)
			.toContain('const styled: __PikaTypegenUnit0.Pika')
		expect(typegen)
			.toBe(typegenBeforeUsage)

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('color: red')
		expect(await readFile(ctx.tsCodegenFilepath!, 'utf8'))
			.toContain('const styled: __PikaTypegenUnit0.Pika')

		await withProcessCwd(cwd, async () => ctx.fullyCssCodegen())
		expect(ctx.getScannedButNotTransformedFiles())
			.toContain(join(cwd, 'src/a.ts'))
		await ctx.dropModule('src/a.ts')
		expect(ctx.usages.size)
			.toBe(0)
	})

	it('publishes canonical Typegen even when the legacy tsCodegen option is disabled', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.ts'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			tsCodegen: false,
		}))

		// Before generation capture, source-target checks remain broad. Canonical
		// Typegen capture then derives and publishes the project regardless of the
		// superseded host-level `tsCodegen` disable flag.
		expect(ctx.resolvedConfig)
			.toBeNull()
		expect(ctx.isTransformTarget('src/cold.ts'))
			.toBe(true)
		expect(ctx.isTransformTarget('src/cold.css'))
			.toBe(false)
		const typegen = await ctx.getTsCodegenContent()
		expect(typegen)
			.toContain('// Auto-generated by PikaCSS')
		expect(ctx.tsCodegenFilepath)
			.toBe(join(cwd, '.pikacss/pika.gen.ts'))
		expect(await readFile(ctx.tsCodegenFilepath!, 'utf8'))
			.toBe(typegen)

		await ctx.setup()
		expect(await ctx.transform(`export const ignored = pika({ color: 'red' })`, 'outside/ignored.ts'))
			.toBeNull()
	})

	it('filters canonical Vue subrequests and generated TypeScript outputs inside the captured generation', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.{ts,vue}'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			tsCodegen: 'src/pika.gen.ts',
		}))
		await ctx.setup()

		expect(await ctx.transform(
			`export const cls = pika({ color: 'red' })`,
			join(cwd, 'src/App.vue?vue&type=script&lang.ts'),
		))
			.toBeNull()
		expect(await ctx.transform(
			`export const generated = pika({ color: 'red' })`,
			ctx.tsCodegenFilepath!,
		))
			.toBeNull()
		expect(ctx.usages.size)
			.toBe(0)
	})

	it('treats deletion of an unknown canonical module as an ordered empty transaction', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.ts'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		await expect(ctx.dropModule('src/never-seen.ts'))
			.resolves.toBeUndefined()
		expect(ctx.usages.size)
			.toBe(0)
	})

	it('commits one physical source across multiple entries as one project transaction', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig([
				{ fnName: 'pika', cssModule: 'pika.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
				{ fnName: 'admin', cssModule: 'admin.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
			])
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		expect(await ctx.resolveCssModule('pika.css'))
			.toContain('.pikacss')
		expect(await ctx.resolveCssModule('admin.css'))
			.toContain('.pikacss')
		expect(await ctx.transform('export const plain = 1', 'other/plain.ts'))
			.toBeNull()
		expect(await ctx.transform('export const plain = 1', 'src/plain.ts'))
			.toBeNull()

		const result = await ctx.transform([
			`export const base = pika({ color: 'red' })`,
			`export const scoped = admin({ display: 'flex' })`,
		].join('\n'), 'src/owned.ts')
		expect(result?.code)
			.toContain(`export const base = 'pk-a'`)
		expect(result?.code)
			.toContain(`export const scoped = 'pk-b'`)
		expect(ctx.engine.store.atomicStyles.size)
			.toBe(1)

		// Legacy singular CSS projection remains intentionally unavailable; P2
		// publishes each entry's physical runtime CSS independently.
		await expect(ctx.getCssCodegenContent())
			.rejects.toThrow('multi-entry')
		await ctx.waitForIdle()
	})

	it('restores a same-generation multi-entry cache hit without allocating new atomic IDs', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig([
				{ fnName: 'pika', cssModule: 'pika.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
				{ fnName: 'admin', cssModule: 'admin.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
			])
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()
		const file = join(cwd, 'src/cache.ts')
		const source = `export const cls = pika({ color: 'red' })`

		const first = await ctx.transform(source, file)
		expect(first?.code)
			.toContain(`'pk-a'`)
		const atomicCount = ctx.engine.store.atomicStyles.size
		await ctx.waitForIdle()

		// Simulate a lost projection while preserving the generation-owned
		// committed snapshot. The cache hit must restore it without commitUse.
		ctx.usages.delete(file)
		expect(ctx.usages.has(file))
			.toBe(false)
		const second = await ctx.transform(source, file)
		expect(second?.code)
			.toBe(first?.code)
		expect(ctx.usages.get(file)?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.engine.store.atomicStyles.size)
			.toBe(atomicCount)
		await ctx.waitForIdle()
	})

	it('prepares every participating entry before committing any of them', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig([
				{ fnName: 'pika', cssModule: 'pika.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
				{ fnName: 'admin', cssModule: 'admin.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
			])
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		await expect(ctx.transform([
			`export const base = pika({ color: 'red' })`,
			`export const scoped = admin(() => 'unsupported')`,
		].join('\n'), 'src/atomic.ts'))
			.rejects.toThrow(PikaTransformError)

		// Entry 0 prepared successfully, but entry 1 failed before the shared
		// project slot became commit-ready. No participating Engine may mutate.
		expect(ctx.engine.store.atomicStyles.size)
			.toBe(0)
		expect(ctx.usages.has(join(cwd, 'src/atomic.ts')))
			.toBe(false)
	})

	it('full-scans a multi-entry project as one deterministic project batch and publishes each entry CSS', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/a.ts'), `export const adminCls = admin({ display: 'flex' })\n`)
		await writeFile(join(cwd, 'src/z.ts'), `export const baseCls = pika({ color: 'red' })\n`)
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig([
				{ fnName: 'pika', cssModule: 'pika.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
				{ fnName: 'admin', cssModule: 'admin.css', scan: { include: ['src/**/*.ts'], exclude: [] } },
			])
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		await ctx.fullyCssCodegen()
		const baseCssPath = await ctx.resolveCssModule('pika.css')
		const adminCssPath = await ctx.resolveCssModule('admin.css')
		expect(baseCssPath)
			.not.toBeNull()
		expect(adminCssPath)
			.not.toBeNull()
		const [baseCss, adminCss] = await Promise.all([
			readFile(baseCssPath!, 'utf8'),
			readFile(adminCssPath!, 'utf8'),
		])
		expect(baseCss)
			.toContain('color: red')
		expect(baseCss)
			.not.toContain('display: flex')
		expect(adminCss)
			.toContain('display: flex')
		expect(adminCss)
			.not.toContain('color: red')
	})

	it('replays KnownModule raw source into a detached candidate before config reload activation', async () => {
		const cwd = await createTempDir()
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, projectConfigSource(`
			export default defineConfig({
				scan: { include: ['src/**/*.ts'], exclude: [] },
			})
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		const source = `export const cls = pika({ color: 'red' })`
		const first = await ctx.transform(source, 'src/replay.ts')
		expect(first?.code)
			.toContain(`'pk-a'`)
		await ctx.waitForIdle()

		await writeFile(configPath, projectConfigSource(`
			export default defineConfig({
				scan: { include: ['src/**/*.ts'], exclude: [] },
				engine: { prefix: 'next-' },
			})
		`))
		await ctx.setup()

		// The new generation is already semantically complete when activation
		// returns; no post-activation source transform is required to rebuild it.
		expect(ctx.usages.get(join(cwd, 'src/replay.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['next-a'])
		const cssPath = await ctx.resolveCssModule('pika.css')
		const css = await readFile(cssPath!, 'utf8')
		expect(css)
			.toContain('.next-a')
		expect(css)
			.toContain('color: red')
	})

	it('replays only KnownModules that still match the detached candidate scan', async () => {
		const cwd = await createTempDir()
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.ts'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()
		await ctx.transform(`export const cls = pika({ color: 'red' })`, 'src/old.ts')
		await ctx.waitForIdle()

		await writeFile(configPath, projectConfigSource(`
			export default defineConfig({ scan: { include: ['next/**/*.ts'], exclude: [] } })
		`))
		await ctx.setup()

		expect(ctx.usages.has(join(cwd, 'src/old.ts')))
			.toBe(false)
		const cssPath = await ctx.resolveCssModule('pika.css')
		expect(await readFile(cssPath!, 'utf8'))
			.not.toContain('color: red')
	})

	it('keeps canonical full-scan atomic IDs in source order when prepares finish out of order', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/a-red.ts'), `export const cls = pika({ color: 'red' })\n`)
		await writeFile(join(cwd, 'src/z-blue.ts'), `export const cls = pika({ color: 'blue' })\n`)
		const blueStarted = createDeferred()
		const gateKey = `__pikacss_batch_order_${Math.random()
			.toString(36)
			.slice(2)}`
		;(globalThis as any)[gateKey] = {
			blueStarted: () => blueStarted.resolve(),
			waitForBlue: blueStarted.promise,
		}
		try {
			await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
				export default defineConfig({
					scan: { include: ['src/**/*.ts'], exclude: [] },
					engine: { plugins: [{
						name: 'test:scrambled-project-prepare',
						async transformStyleItems(items) {
							const color = items.map(item => typeof item === 'object' && item != null ? item.color : undefined)
								.find(value => typeof value === 'string')
							const gate = globalThis[${JSON.stringify(gateKey)}]
							if (color === 'blue') gate.blueStarted()
							if (color === 'red') await gate.waitForBlue
							return items
						},
					}] },
				})
			`))
			const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
			await ctx.setup()
			await ctx.fullyCssCodegen()

			expect(ctx.usages.get(join(cwd, 'src/a-red.ts'))?.[0]?.atomicStyleIds)
				.toEqual(['pk-a'])
			expect(ctx.usages.get(join(cwd, 'src/z-blue.ts'))?.[0]?.atomicStyleIds)
				.toEqual(['pk-b'])
		}
		finally {
			delete (globalThis as any)[gateKey]
		}
	})

	it('commits a missing file as an empty contribution on a repeated canonical full scan', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		const sourcePath = join(cwd, 'src/removed.ts')
		await writeFile(sourcePath, `export const cls = pika({ color: 'red' })\n`)
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.ts'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()
		await ctx.fullyCssCodegen()
		expect(ctx.usages.has(sourcePath))
			.toBe(true)
		let css = await readFile((await ctx.resolveCssModule('pika.css'))!, 'utf8')
		expect(css)
			.toContain('color: red')

		await rm(sourcePath)
		await ctx.fullyCssCodegen()
		expect(ctx.usages.has(sourcePath))
			.toBe(false)
		css = await readFile((await ctx.resolveCssModule('pika.css'))!, 'utf8')
		expect(css)
			.not.toContain('color: red')
	})

	it('aborts a canonical full-scan batch before any source commits when one prepare fails', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/a-good.ts'), `export const cls = pika({ color: 'red' })\n`)
		await writeFile(join(cwd, 'src/z-bad.ts'), `export const cls = pika({ boom: 'yes' })\n`)
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({
				scan: { include: ['src/**/*.ts'], exclude: [] },
				engine: { plugins: [{
					name: 'test:batch-failure',
					transformStyleItems(items) {
						if (items.some(item => typeof item === 'object' && item != null && 'boom' in item))
							throw new Error('batch exploded')
						return items
					},
				}] },
			})
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		await expect(ctx.fullyCssCodegen())
			.rejects.toThrow('batch exploded')
		expect(ctx.engine.store.atomicStyles.size)
			.toBe(0)
		expect(ctx.usages.size)
			.toBe(0)
	})

	it('retains the complete previous generation when detached KnownModule replay fails', async () => {
		const cwd = await createTempDir()
		const gateKey = `__pikacss_replay_failure_${Math.random()
			.toString(36)
			.slice(2)}`
		;(globalThis as any)[gateKey] = { fail: false }
		const configPath = join(cwd, 'pika.config.ts')
		const config = (prefix: string) => projectConfigSource(`
			export default defineConfig({
				scan: { include: ['src/**/*.ts'], exclude: [] },
				engine: {
					prefix: ${JSON.stringify(prefix)},
					plugins: [{
						name: 'test:replay-failure',
						transformStyleItems(items) {
							if (globalThis[${JSON.stringify(gateKey)}].fail)
								throw new Error('candidate replay exploded')
							return items
						},
					}],
				},
			})
		`)

		try {
			await writeFile(configPath, config('old-'))
			const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
			ctx.configErrorBehavior = 'retain-last-good'
			await ctx.setup()
			await ctx.transform(`export const cls = pika({ color: 'red' })`, 'src/replay-fail.ts')
			await ctx.waitForIdle()
			const previousEngine = ctx.engine
			const previousCssPath = await ctx.resolveCssModule('pika.css')
			expect(ctx.usages.get(join(cwd, 'src/replay-fail.ts'))?.[0]?.atomicStyleIds)
				.toEqual(['old-a'])

			;(globalThis as any)[gateKey].fail = true
			await writeFile(configPath, config('next-'))
			await ctx.setup()

			expect(ctx.engine)
				.toBe(previousEngine)
			expect(await ctx.resolveCssModule('pika.css'))
				.toBe(previousCssPath)
			expect(ctx.usages.get(join(cwd, 'src/replay-fail.ts'))?.[0]?.atomicStyleIds)
				.toEqual(['old-a'])
			const css = await readFile(previousCssPath!, 'utf8')
			expect(css)
				.toContain('.old-a')
			expect(css)
				.not.toContain('.next-a')
		}
		finally {
			delete (globalThis as any)[gateKey]
		}
	})

	it('uses the bundler project host for live dependency and activation handshakes', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({
				fnName: 'pika',
				cssModule: 'pika.css',
				scan: { include: ['src/**/*.ts'], exclude: [] },
			})
		`))
		const armed: string[] = []
		const activations: Array<{ sourceIds: readonly string[], cssModules: readonly string[], runtimeCssFilepaths: readonly string[] }> = []
		let cssPublishedAtActivation = false
		const ctxRef: { current?: ReturnType<typeof createCtx> } = {}
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			projectHost: {
				mode: () => 'live',
				armDependencies: (dependencies) => { armed.push(...dependencies.map(dependency => dependency.path)) },
				async onActivated(activation) {
					activations.push(activation)
					const cssPath = await ctxRef.current!.resolveCssModule('pika.css')
					cssPublishedAtActivation = cssPath != null && await stat(cssPath)
						.then(() => true, () => false)
				},
			},
		}))
		ctxRef.current = ctx

		await ctx.setup()
		expect(armed)
			.toContain(join(cwd, 'pika.config.ts'))
		expect(activations)
			.toHaveLength(1)
		expect(activations[0]!.cssModules)
			.toEqual(['pika.css'])
		expect(activations[0]!.runtimeCssFilepaths)
			.toEqual([ctx.cssCodegenFilepath])
		expect(cssPublishedAtActivation)
			.toBe(true)
	})

	it('surfaces a live cold-start derivation failure through the compatibility error policy', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), 'export default {}\n')
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			projectHost: {
				mode: () => 'live',
				armDependencies: () => {},
			},
		}))
		ctx.configErrorBehavior = 'throw'

		await expect(ctx.setup()).rejects.toThrow('defineConfig')
	})

	it('keeps the canonical idle barrier open until an in-flight transform settles', async () => {
		const cwd = await createTempDir()
		const reached = createDeferred()
		const release = createDeferred()
		const gateKey = `__pikacss_ctx_gate_${Math.random()
			.toString(36)
			.slice(2)}`
		;(globalThis as any)[gateKey] = {
			reach: () => reached.resolve(),
			wait: release.promise,
		}
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({
				scan: { include: ['src/**/*.ts'], exclude: [] },
				engine: { plugins: [{
					name: 'test:idle-gate',
					async transformStyleItems(items) {
						const gate = globalThis[${JSON.stringify(gateKey)}]
						gate.reach()
						await gate.wait
						return items
					},
				}] },
			})
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))

		try {
			await ctx.setup()
			const transforming = ctx.transform(`export const cls = pika({ color: 'red' })`, 'src/gated.ts')
			await reached.promise
			expect(ctx.isIdle)
				.toBe(false)

			let idleResolved = false
			const idle = ctx.waitForIdle()
				.then(() => { idleResolved = true })
			await Promise.resolve()
			expect(idleResolved)
				.toBe(false)

			release.resolve()
			await transforming
			await idle
			expect(ctx.isIdle)
				.toBe(true)
		}
		finally {
			delete (globalThis as any)[gateKey]
		}
	})

	it('publishes engine update hooks only for the currently active generation', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.ts'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)
		await ctx.setup()
		onStyleUpdated.mockClear()

		const retiredEngine = ctx.engine
		retiredEngine.addPreflight({ body: { color: 'red' } })
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		await ctx.setup()
		expect(ctx.engine).not.toBe(retiredEngine)
		onStyleUpdated.mockClear()
		await retiredEngine.use({ color: 'purple' })
		expect(onStyleUpdated).not.toHaveBeenCalled()
	})

	it('does not discover a config file nested in a subdirectory (root-only discovery)', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'fixtures'), { recursive: true })
		await writeFile(join(cwd, 'fixtures/pika.config.ts'), 'export default {}\n')
		log.setWarnFn(vi.fn())

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBeNull()
	})

	it('resolves null when no function call matches and rejects when argument evaluation fails', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		expect(await ctx.transform('const plain = 1', 'src/plain.ts'))
			.toBeNull()

		const valid = await ctx.transform('const value = pika({ color: \'red\' })', 'src/broken.ts')
		expect(valid)
			.toBeDefined()
		expect(ctx.usages.has(join(cwd, 'src/broken.ts')))
			.toBe(true)

		await expect(ctx.transform('const broken = pika(foo())', 'src/broken.ts'))
			.rejects.toThrow(PikaTransformError)
		// The previously committed usages stay intact (last-good retention).
		expect(ctx.usages.get(join(cwd, 'src/broken.ts')))
			.toHaveLength(1)
	})

	it('triggers regeneration when the last style call is removed from a file', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)

		await ctx.transform('const value = pika({ color: \'red\' })', 'src/removed.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		await ctx.transform('const value = 1', 'src/removed.ts')
		expect(ctx.usages.has(join(cwd, 'src/removed.ts')))
			.toBe(false)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)
	})

	it('skips update triggers when a re-transform yields identical usages', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		await ctx.transform('// rev 1\nconst a = pika({ color: \'red\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		// Different code (comment edit) but identical pika() usages: no triggers.
		await ctx.transform('// rev 2\nconst a = pika({ color: \'red\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(ctx.usages.get(join(cwd, 'src/resave.ts')))
			.toHaveLength(1)

		// Changed usages still fire the style hook.
		await ctx.transform('// rev 3\nconst a = pika({ color: \'blue\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)

		// A different number of calls fires (length short-circuit in the compare).
		await ctx.transform('// rev 4\nconst a = pika({ color: \'blue\' })\nconst b = pika({ margin: \'1px\' })', 'src/resave.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(3)

		// The typegen hook never fires from source transforms: declarations do
		// not depend on usage state (#113).
		expect(onTsUpdated)
			.not.toHaveBeenCalled()
	})

	it('reuses the memoized transform result for identical inputs and recomputes when they change', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const useSpy = vi.spyOn(ctx.engine, 'prepareUse')

		const code = 'const a = pika({ color: \'red\' })'
		const first = await ctx.transform(code, 'src/memo.ts')
		expect(useSpy)
			.toHaveBeenCalledTimes(1)

		// Same (id, code): the engine work happens once and the cached
		// replacements are reused (the result object itself is rebuilt).
		const second = await ctx.transform(code, 'src/memo.ts')
		expect(useSpy)
			.toHaveBeenCalledTimes(1)
		expect(second?.code)
			.toBe(first?.code)

		// Different code recomputes.
		await ctx.transform('const a = pika({ color: \'blue\' })', 'src/memo.ts')
		expect(useSpy)
			.toHaveBeenCalledTimes(2)

		// setup() swaps the engine and clears the memo: identical code recomputes.
		await ctx.setup()
		const useSpyAfterSetup = vi.spyOn(ctx.engine, 'prepareUse')
		await ctx.transform(code, 'src/memo.ts')
		expect(useSpyAfterSetup)
			.toHaveBeenCalledTimes(1)
	})

	it('restores externally dropped usages when a memoized identical file is re-transformed', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const code = [
			'const a = pika({ color: \'red\' })',
			'const b = pika({ color: \'green\' })',
		].join('\n')
		await ctx.transform(code, 'src/deleted.ts')
		expect(ctx.usages.get(join(cwd, 'src/deleted.ts')))
			.toHaveLength(2)

		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)

		// Simulate the bundler reporting the file as deleted (watchChange path).
		ctx.usages.delete(join(cwd, 'src/deleted.ts'))

		await ctx.transform(code, 'src/deleted.ts')
		expect(ctx.usages.get(join(cwd, 'src/deleted.ts')))
			.toHaveLength(2)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
	})

	it('rejects the whole module and commits nothing when a sibling call fails to evaluate', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// Module transforms are atomic: one failing call rejects the module and
		// the valid sibling call is not committed either.
		await expect(ctx.transform([
			'const ok = pika({ color: \'red\' })',
			'const broken = pika({ color: localVariable })',
		].join('\n'), 'src/partial.ts'))
			.rejects.toThrow(PikaTransformError)
		expect(ctx.usages.has(join(cwd, 'src/partial.ts')))
			.toBe(false)
	})

	it('rejects legacy bracket member calls as reserved compile-time syntax', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		await expect(ctx.transform(
			'const a = pika[\'str\']({ color: \'red\' })',
			'src/legacy.ts',
		))
			.rejects.toMatchObject({ stage: 'collect' })
		expect(ctx.usages.has(join(cwd, 'src/legacy.ts')))
			.toBe(false)
	})

	it('handles nested static templates and comments while transforming base calls', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			transformedFormat: 'array',
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'const a = pika({ color: \'red\' /* inline comment */ })',
			'const b = pika({ content: `calc(${`1`})` })',
			'const c = pika({ color: \'blue\' // trailing comment\n})',
		].join('\n'), 'src/complex.ts')

		expect(transformed?.code)
			.toContain('[')
		expect(transformed?.code.includes('pika('))
			.toBe(false)
		expect(ctx.usages.get(join(cwd, 'src/complex.ts')))
			.toHaveLength(3)
	})

	it('transforms pika() calls inside Vue SFC template attributes', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.{ts,vue}'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<script setup lang="ts">',
			'const fromScript = pika({ color: \'gold\' })',
			'</script>',
			'',
			'<template>',
			'\t<!-- <div :class="pika({ color: \'red\' })"> -->',
			'\t<div :class="pika({ height: \'100vh\', display: \'flex\' })">',
			'\t\t<span :class="pika({ fontSize: \'0.875rem\' })">text</span>',
			'\t</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		expect(transformed?.code.includes('pika({ color: \'gold\' })'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ height:'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ fontSize:'))
			.toBe(false)
		// The commented-out call must survive untouched.
		expect(transformed?.code)
			.toContain('<!-- <div :class="pika({ color: \'red\' })"> -->')
		// Replacements must stay single-quoted inside double-quoted attributes.
		expect(transformed?.code)
			.toMatch(/:class="'[^"]*'"/)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(3)
	})

	it('escapes line terminators when serializing unresolved string style items', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// `new Function` evaluation turns the source `\n` escape into a real LF,
		// which the engine echoes back verbatim for unresolved string items.
		const transformed = await ctx.transform('const value = pika(\'a\\nb\')', 'src/newline.ts')

		expect(transformed?.code)
			.toContain('\'a\\nb\'')
		// The emitted literal must not contain a raw line terminator.
		expect(transformed?.code)
			.not.toContain('\n')
		// eslint-disable-next-line no-new-func
		expect(() => new Function(transformed!.code))
			.not.toThrow()
	})

	it('does not rewrite pika lookalikes inside script-block literals and comments of markup sources', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<script setup lang="ts">',
			'const tip = "use pika(\'bg:red\') here"',
			'// pika({ color: \'red\' })',
			'/* pika({ color: \'green\' }) */',
			'const real = pika({ color: \'gold\' })',
			'</script>',
			'',
			'<template>',
			'\t<div :class="pika({ color: \'blue\' })">real</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		// Lookalikes inside script-block literals and JS comments survive untouched.
		expect(transformed?.code)
			.toContain('const tip = "use pika(\'bg:red\') here"')
		expect(transformed?.code)
			.toContain('// pika({ color: \'red\' })')
		expect(transformed?.code)
			.toContain('/* pika({ color: \'green\' }) */')
		// Real calls in the script block and the template attribute are rewritten.
		expect(transformed?.code.includes('pika({ color: \'gold\' })'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ color: \'blue\' })'))
			.toBe(false)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(2)
	})

	it('emits double-quoted literals inside single-quoted markup attributes', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<template>',
			'\t<div :class=\'pika({ color: "red" })\'>',
			'\t\t<span :class="pika({ color: \'blue\' })">text</span>',
			'\t</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		// Single-quoted attribute stays intact: the literal uses double quotes.
		expect(transformed?.code)
			.toMatch(/:class='"[^']*"'/)
		// Double-quoted attribute keeps the existing single-quoted output.
		expect(transformed?.code)
			.toMatch(/:class="'[^"]*'"/)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(2)
	})

	it('keeps single-quoted output for a double-quoted attribute containing a string comparison', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		// Regression: the `== 'dark'` comparison used to make the quote detector
		// pick `"`, emitting a double-quoted literal into the double-quoted
		// attribute and breaking it. The literal must stay single-quoted.
		const transformed = await ctx.transform([
			'<template>',
			'\t<div :class="mode == \'dark\' ? pika({ color: \'white\' }) : \'\'">x</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		expect(transformed?.code)
			.toMatch(/\?\s*'[^"]*'\s*:/)
		// The double-quoted :class attribute is not closed early by the literal.
		expect(transformed?.code)
			.not.toMatch(/:class="[^"]*"[^"]*"/)
		expect(ctx.usages.get(join(cwd, 'src/App.vue')))
			.toHaveLength(1)
	})

	it('buffers style and ts updates until all concurrent transforms finish', async () => {
		const firstUse = createDeferred<string[]>()
		const secondUse = createDeferred<string[]>()
		let useCallCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				const devPlugin = config.plugins?.find((plugin: any) => plugin.name === '@pikacss/integration:dev')
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					// The pipeline drives the split phases directly (#114): the
					// deferred suspends the provisional phase, and the sync commit
					// phase turns the resolved ids into the returned names while
					// firing the committed notifications.
					prepareUse: vi.fn(async () => {
						useCallCount++
						return useCallCount === 1 ? firstUse.promise : secondUse.promise
					}),
					commitUse: vi.fn((ids: string[]) => {
						devPlugin?.atomicStyleAdded?.()
						devPlugin?.autocompleteConfigUpdated?.()
						return ids
					}),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const options = createOptions()
		const ctx = createMockedCtx(options)

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		const firstTransform = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		const secondTransform = ctx.transform('const b = pika({ color: \'blue\' })', 'src/b.ts')

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		firstUse.resolve(['pk-a'])
		await firstTransform

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		secondUse.resolve(['pk-b'])
		await secondTransform

		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.not.toHaveBeenCalled()
		expect(ctx.usages.get(join(options.cwd, 'src/a.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.usages.get(join(options.cwd, 'src/b.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-b'])
	})

	it('waits for the remaining transform when a concurrent transform fails early', async () => {
		const firstUse = createDeferred<string[]>()

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				const devPlugin = config.plugins?.find((plugin: any) => plugin.name === '@pikacss/integration:dev')
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					prepareUse: vi.fn(async () => firstUse.promise),
					commitUse: vi.fn((ids: string[]) => {
						devPlugin?.atomicStyleAdded?.()
						devPlugin?.autocompleteConfigUpdated?.()
						return ids
					}),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const options = createOptions()
		const ctx = createMockedCtx(options)

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		const firstTransform = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		const failedTransform = ctx.transform('const broken = pika(foo())', 'src/b.ts')

		// `vi.resetModules()` gives the re-imported ctx its own error class
		// identity, so match on the message instead of the constructor.
		await expect(failedTransform)
			.rejects.toThrow('Failed to statically evaluate pika() argument')

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		firstUse.resolve(['pk-a'])
		await firstTransform

		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.not.toHaveBeenCalled()
		expect(ctx.usages.get(join(options.cwd, 'src/a.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.usages.has(join(options.cwd, 'src/b.ts')))
			.toBe(false)
	})

	it('drains in-flight transforms before setup clears state and swaps the engine', async () => {
		const firstUse = createDeferred<string[]>()
		let engineCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				engineCount++
				const engineIndex = engineCount
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					prepareUse: vi.fn(async () => engineIndex === 1 ? firstUse.promise : ['pk-new']),
					commitUse: vi.fn((ids: string[]) => ids),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const options = createOptions()
		const ctx = createMockedCtx(options)

		await ctx.setup()

		// Suspended at the first engine's `use()` call.
		const inFlight = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')

		let setupDone = false
		const setupPromise = ctx.setup()
			.then(() => {
				setupDone = true
			})

		// Setup must stay parked on the drain while the transform is in flight.
		await new Promise(resolve => setTimeout(resolve, 10))
		expect(setupDone)
			.toBe(false)

		firstUse.resolve(['pk-old'])
		await inFlight
		await setupPromise

		// The late transform completed before setup cleared state, so its
		// old-engine usages were not written into the new engine's session.
		expect(ctx.usages.size)
			.toBe(0)

		// A re-transform after setup records usages resolved by the new engine.
		await ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		expect(ctx.usages.get(join(options.cwd, 'src/a.ts'))?.[0]?.atomicStyleIds)
			.toEqual(['pk-new'])
	})

	it('exposes idle state via isIdle and resolves waitForIdle once in-flight transforms settle', async () => {
		const firstUse = createDeferred<string[]>()
		let useCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => ({
				config,
				store: {
					atomicStyleIds: new Map(),
				},
				prepareUse: vi.fn(async () => {
					useCount++
					return useCount === 1 ? firstUse.promise : ['pk-a']
				}),
				commitUse: vi.fn((ids: string[]) => ids),
				renderLayerOrderDeclaration: vi.fn(() => ''),
				renderPreflights: vi.fn(async () => ''),
				renderAtomicStyles: vi.fn(async () => ''),
			}))

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions())

		await ctx.setup()

		// Idle context: the sync flag is set and waitForIdle resolves immediately.
		expect(ctx.isIdle)
			.toBe(true)
		await ctx.waitForIdle()

		// Suspended at the engine's `use()` call: the context reports busy and
		// waitForIdle stays pending until the transform settles.
		const inFlight = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		await new Promise(resolve => setTimeout(resolve, 0))
		expect(ctx.isIdle)
			.toBe(false)

		let idleResolved = false
		const idlePromise = ctx.waitForIdle()
			.then(() => {
				idleResolved = true
			})
		await new Promise(resolve => setTimeout(resolve, 10))
		expect(idleResolved)
			.toBe(false)

		firstUse.resolve(['pk-a'])
		await inFlight
		await idlePromise
		expect(idleResolved)
			.toBe(true)
		expect(ctx.isIdle)
			.toBe(true)
	})

	it('rejects unparsable sources and ignores pika lookalikes inside comments and strings', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// Lookalikes inside comments and string literals never match under AST
		// semantics: no macro call is collected and the module resolves null.
		expect(await ctx.transform([
			'// pika({ color: \'red\' })',
			'/* pika({ color: \'green\' }) */',
			'const tip = "use pika(\'bg:red\') here"',
		].join('\n'), 'src/lookalikes.ts'))
			.toBeNull()
		expect(ctx.usages.has(join(cwd, 'src/lookalikes.ts')))
			.toBe(false)

		// Genuinely malformed sources are parse hard-errors.
		await expect(ctx.transform('const a = pika({ color: `red ${`', 'src/malformed-template.ts'))
			.rejects.toThrow(PikaTransformError)
		await expect(ctx.transform('const b = pika({ color: \'red\' /*', 'src/unclosed-comment.ts'))
			.rejects.toThrow(PikaTransformError)
		await expect(ctx.transform('const c = pika({', 'src/unterminated-call.ts'))
			.rejects.toThrow(PikaTransformError)
	})

	it('skips TypeScript generation when it is disabled and performs full CSS scanning', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src', 'demo.ts'), 'export const value = pika({ color: \'red\' })')
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('/* Auto-generated by @pikacss/core */')
		expect(ctx.transformFilter.exclude)
			.toEqual(['.pikacss/**'])
		ctx.dropModule('src/not-collected.ts')
	})

	it('evaluates transform targets against the current cwd and always rejects codegen outputs', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['**/*.{ts,css}'],
				exclude: ['node_modules/**', 'dist/**', join(nextCwd, 'abs-excluded/**')],
			},
		}))

		// Relative excludes and ids must follow the updated cwd, not the one the
		// context was created with.
		ctx.cwd = nextCwd

		expect(ctx.isTransformTarget(join(nextCwd, 'src/demo.ts')))
			.toBe(true)
		// Relative ids resolve against the current cwd.
		expect(ctx.isTransformTarget('src/demo.ts'))
			.toBe(true)
		// Query/hash suffixes are ignored.
		expect(ctx.isTransformTarget(`${join(nextCwd, 'src/demo.ts')}?raw`))
			.toBe(true)
		// cwd-relative excludes are resolved against the current cwd.
		expect(ctx.isTransformTarget(join(nextCwd, 'node_modules/pkg/index.ts')))
			.toBe(false)
		expect(ctx.isTransformTarget(join(nextCwd, 'dist/out.ts')))
			.toBe(false)
		// Codegen outputs are always rejected, even when they match the include globs.
		expect(ctx.isTransformTarget(join(nextCwd, 'generated/pika.gen.ts')))
			.toBe(false)
		// Internal runtime state (including the invocation-owned CSS) is always
		// rejected via the default `.pikacss/**` exclude.
		expect(ctx.isTransformTarget(ctx.cssCodegenFilepath))
			.toBe(false)
		expect(ctx.isTransformTarget(join(nextCwd, '.pikacss/internal-note.css')))
			.toBe(false)
		// Absolute exclude patterns match against the absolute id.
		expect(ctx.isTransformTarget(join(nextCwd, 'abs-excluded/skip.ts')))
			.toBe(false)
		// Non-included files are rejected.
		expect(ctx.isTransformTarget(join(nextCwd, 'README.md')))
			.toBe(false)
	})

	it('skips the codegen output files during full CSS scanning even when they match scan.include', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/demo.ts'), 'export const value = pika({ color: \'red\' })')
		// A stale codegen output that matches the include glob must not be scanned.
		const tsCodegenFilepath = join(cwd, 'src/pika.gen.ts')
		await writeFile(tsCodegenFilepath, 'export const leaked = pika({ color: \'blue\' })')

		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: 'src/pika.gen.ts',
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(ctx.usages.has(tsCodegenFilepath))
			.toBe(false)
		const css = await readFile(ctx.cssCodegenFilepath, 'utf8')
		expect(css)
			.toContain('color: red')
		expect(css)
			.not.toContain('color: blue')
	})

	it('prunes variables and keyframes of styles whose usages were removed', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: {
				variables: {
					definitions: {
						'--main-color': { value: 'red' },
					},
				},
				keyframes: {
					definitions: [
						{ name: 'spin', frames: { from: { opacity: '0' }, to: { opacity: '1' } } },
					],
				},
			},
		}))

		await ctx.setup()

		await ctx.transform('const a = pika({ color: \'var(--main-color)\', animationName: \'spin\' })', 'src/anim.ts')
		const withUsage = await ctx.getCssCodegenContent()
		expect(withUsage)
			.toContain('--main-color')
		expect(withUsage)
			.toContain('@keyframes spin')

		// Deleting the usage (as watchChange/transform would) must drop the
		// variable and keyframes from the regenerated CSS despite the
		// append-only engine store.
		await ctx.transform('const a = 1', 'src/anim.ts')
		const withoutUsage = await ctx.getCssCodegenContent()
		expect(withoutUsage)
			.not.toContain('--main-color')
		expect(withoutUsage)
			.not.toContain('@keyframes spin')
	})

	it('honors explicit config paths and leaves tsCodegen excludes empty when disabled', async () => {
		const cwd = await createTempDir()
		const configPath = join(cwd, 'configs/pikacss.config.ts')
		await mkdir(join(cwd, 'configs'), { recursive: true })
		await writeFile(configPath, projectConfigSource(`
			export default defineConfig({
				engine: { preflights: [{ body: { color: 'purple' } }] },
				scan: { include: ['src/**/*.ts'], exclude: [] },
			})
		`))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: 'configs/pikacss.config.ts',
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		// Canonical configured scan semantics are only known after Config-host
		// evaluation, so the adapter prefilter stays broad.
		expect(ctx.transformFilter.exclude)
			.toEqual([])
		expect(await ctx.getCssCodegenContent())
			.toContain('color: purple;')
	})

	it('ignores a previous-root activation that finishes after a new runtime is created', async () => {
		const rootA = await createTempDir()
		const rootB = await createTempDir()
		const entered = createDeferred<void>()
		const release = createDeferred<void>()
		;(globalThis as any).__pikaRootRace = {
			entered: () => entered.resolve(),
			wait: release.promise,
		}

		try {
			await writeFile(join(rootA, 'pika.config.ts'), projectConfigSource(`
				export default defineConfig({
					engine: {
						prefix: 'a-',
						plugins: [{
							name: 'test:delayed-root-a',
							async configureEngine() {
								globalThis.__pikaRootRace.entered()
								await globalThis.__pikaRootRace.wait
							},
						}],
					},
				})
			`))
			await writeFile(join(rootB, 'pika.config.ts'), projectConfigSource(`
				export default defineConfig({ engine: { prefix: 'b-' } })
			`))

			const ctx = createCtx(createOptions({
				cwd: rootA,
				configOrPath: null,
				tsCodegen: false,
			}))
			const typegenUpdates = vi.fn()
			ctx.hooks.tsCodegenUpdated.on(typegenUpdates)

			const setupA = ctx.setup()
			await entered.promise

			// Creating semantic work after the cwd switch creates runtime B while
			// runtime A is still inside configureEngine. A's later activation must
			// not repopulate the facade or emit host-facing hooks.
			ctx.cwd = rootB
			const transformB = ctx.transform(
				`export const cls = pika({ color: 'red' })`,
				'src/b.ts',
			)
			release.resolve()

			await setupA
			expect(await transformB)
				.not.toBeNull()
			expect(ctx.engine.config.prefix)
				.toBe('b-')
			expect(ctx.resolvedConfigPath)
				.toBe(join(rootB, 'pika.config.ts'))
			// Canonical Typegen publication is generation-owned and no longer emits
			// the legacy runtime regeneration hook from either activation.
			expect(typegenUpdates)
				.not.toHaveBeenCalled()
		}
		finally {
			delete (globalThis as any).__pikaRootRace
		}
	})

	it('treats missing auto config as the canonical default project and rejects an invalid explicit extension', async () => {
		const cwd = await createTempDir()
		const defaultProject = createCtx(createOptions({ cwd, configOrPath: null, tsCodegen: false }))
		const invalidExt = createCtx(createOptions({ cwd, configOrPath: 'pika.config.txt' }))

		await withProcessCwd(cwd, async () => {
			expect(await defaultProject.loadConfig())
				.toEqual({ config: {}, file: null, content: null })
			await expect(invalidExt.loadConfig())
				.rejects.toThrow('extension')
		})

		expect(defaultProject.resolvedConfigPath)
			.toBeNull()
	})

	it('sets up a default engine config when no config file is available', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfig)
			.toEqual({})
		expect(ctx.engine.config.plugins?.some(plugin => plugin.name === '@pikacss/integration:dev'))
			.toBe(true)
	})

	it('build mode: rejects setup instead of falling back when the config file fails to evaluate', async () => {
		const cwd = await createTempDir()
		log.setErrorFn(vi.fn())
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, 'throw new Error("invalid config")')

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))
		ctx.configErrorBehavior = 'throw'

		await withProcessCwd(cwd, async () => {
			await expect(ctx.setup())
				.rejects
				.toThrow('invalid config')
		})
		// A failed build setup must not leave a usable engine behind.
		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
	})

	it('build mode: rejects setup when engine creation fails instead of falling back to defaults', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			return {
				...actual,
				createEngine: vi.fn(async () => {
					throw new Error('engine boom')
				}),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		core.log.setErrorFn(vi.fn())
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-build-throw',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			autoCreateConfig: false,
		})
		ctx.configErrorBehavior = 'throw'

		await expect(ctx.setup())
			.rejects
			.toThrow('engine boom')
		// The plugin-only default fallback must not run in build mode.
		expect((core.createEngine as any).mock.calls)
			.toHaveLength(1)
	})

	it('dev mode: retains the last known good engine when a config reload fails, then recovers', async () => {
		const cwd = await createTempDir()
		log.setErrorFn(vi.fn())
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, projectConfigSource(`export default defineConfig({})`))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))
		// Default behavior is 'retain-last-good'; assert it explicitly.
		expect(ctx.configErrorBehavior)
			.toBe('retain-last-good')

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			const goodEngine = ctx.engine

			// Break the config and reload: the engine must be retained untouched.
			await writeFile(configPath, 'throw new Error("broke it")')
			await ctx.setup()
			expect(ctx.engine)
				.toBe(goodEngine)
			expect(ctx.resolvedConfig)
				.toEqual({})

			// Fix the config and reload: the engine is rebuilt (recovery).
			await writeFile(configPath, projectConfigSource(`export default defineConfig({})`))
			await ctx.setup()
			expect(ctx.engine)
				.not
				.toBe(goodEngine)
		})
	})

	it('skips writing generated files when the derived content is null', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		vi.spyOn(ctx, 'getCssCodegenContent')
			.mockResolvedValueOnce(null)
		vi.spyOn(ctx, 'getTsCodegenContent')
			.mockResolvedValueOnce(null)

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		await expect(readFile(ctx.cssCodegenFilepath, 'utf8'))
			.rejects
			.toThrow()
		expect(ctx.tsCodegenFilepath)
			.toBe(join(cwd, 'generated/pika.gen.ts'))
	})

	it('returns early when TypeScript codegen is disabled and when css output collapses to only the banner', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await ctx.setup()
		vi.spyOn(ctx.engine, 'renderLayerOrderDeclaration')
			.mockReturnValue('')
		vi.spyOn(ctx.engine, 'renderPreflights')
			.mockResolvedValue('')
		vi.spyOn(ctx.engine, 'renderAtomicStyles')
			.mockResolvedValue('')

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await ctx.getCssCodegenContent())
			.toBe('/* Auto-generated by @pikacss/core */')

		await ctx.writeTsCodegenFile()
	})

	it('retries engine creation with a default plugin-only config when the initial createEngine call fails', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, unknown>) => {
				if (createEngine.mock.calls.length === 1) {
					throw new Error('boom')
				}

				return {
					config,
					use: vi.fn(async () => []),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect((core.createEngine as any).mock.calls)
			.toHaveLength(2)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins)
			.toHaveLength(1)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
	})

	it('logs and clears setupPromise when both engine creation attempts fail', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async () => {
				throw new Error('still broken')
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const error = vi.fn()
		core.log.setErrorFn(error)
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to setup integration context: still broken')))
			.toBe(true)
		expect(ctx.setupPromise)
			.toBeNull()
	})

	it('replaces the declaration file atomically and skips byte-identical rewrites (#112)', async () => {
		const cwd = await createTempDir()
		const calls = { writeFile: 0, rename: 0 }
		let failNextRename = false
		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				writeFile: async (...args: any[]) => {
					calls.writeFile++
					return (actual.writeFile as any)(...args)
				},
				rename: async (...args: any[]) => {
					calls.rename++
					if (failNextRename) {
						failNextRename = false
						throw new Error('EPERM: rename blocked')
					}
					return (actual.rename as any)(...args)
				},
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({ cwd, tsCodegen: 'pika.gen.ts' }))
		await ctx.setup()

		await ctx.writeTsCodegenFile()
		const afterFirstWrite = { ...calls }
		expect(afterFirstWrite.rename)
			.toBe(1)
		const target = ctx.tsCodegenFilepath!
		const { mtimeMs } = await stat(target)

		// Byte-identical declaration: a filesystem no-op — no temp file, no
		// replacement, no mtime churn, no tsserver invalidation.
		await ctx.writeTsCodegenFile()
		expect(calls)
			.toEqual(afterFirstWrite)
		expect((await stat(target)).mtimeMs)
			.toBe(mtimeMs)

		// The temp lives in the target's own directory (same filesystem for a
		// user-configurable path) and never leaves residue. Stale on-disk
		// content forces the writer past the byte-compare; the failed rename
		// then propagates without .tmp leftovers AND without touching the
		// existing target, and the next write replaces it with the complete
		// declaration.
		const initialContent = await readFile(target, 'utf8')
		await writeFile(target, '// stale externally-written content\n')
		failNextRename = true
		await expect(ctx.writeTsCodegenFile())
			.rejects
			.toThrow('rename blocked')
		expect((await readdir(dirname(target))).filter(name => name.endsWith('.tmp')))
			.toEqual([])
		expect(await readFile(target, 'utf8'))
			.toBe('// stale externally-written content\n')
		failNextRename = false
		await ctx.writeTsCodegenFile()
		expect(await readFile(target, 'utf8'))
			.toBe(initialContent)
	})

	it('skips byte-identical runtime CSS rewrites and cleans up when the replacement fails', async () => {
		const cwd = await createTempDir()
		const calls = { writeFile: 0, rename: 0 }
		let failNextRename = false
		let failNextTempWrite = false
		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				writeFile: async (...args: any[]) => {
					calls.writeFile++
					if (failNextTempWrite && typeof args[0] === 'string' && args[0].endsWith('.tmp')) {
						failNextTempWrite = false
						// Leave a partial temp file behind, like an interrupted write.
						await (actual.writeFile as any)(args[0], 'partial')
						throw new Error('ENOSPC: temp write interrupted')
					}
					return (actual.writeFile as any)(...args)
				},
				rename: async (...args: any[]) => {
					calls.rename++
					if (failNextRename) {
						failNextRename = false
						throw new Error('EPERM: rename blocked')
					}
					return (actual.rename as any)(...args)
				},
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))
		await ctx.setup()
		await ctx.transform('export const a = pika({ color: \'red\' })', 'src/a.ts')

		await ctx.writeCssCodegenFile()
		const afterFirstWrite = { ...calls }
		expect(afterFirstWrite.rename)
			.toBe(1)

		// Byte-identical content: the rewrite is a filesystem no-op — no temp
		// file, no replacement, no mtime churn.
		await ctx.writeCssCodegenFile()
		expect(calls)
			.toEqual(afterFirstWrite)

		// A failed replacement removes its unique temp file, propagates the
		// error, and leaves the previous complete stylesheet in place.
		await ctx.transform('export const b = pika({ display: \'flex\' })', 'src/b.ts')
		failNextRename = true
		await expect(ctx.writeCssCodegenFile())
			.rejects
			.toThrow('rename blocked')
		// Temps live in the dedicated .pikacss/tmp directory (outside the
		// watched run directory) and never leave residue behind.
		const listTemps = async () => {
			const runDirTemps = (await readdir(dirname(ctx.cssCodegenFilepath))).filter(name => name.endsWith('.tmp'))
			const tempDirTemps = await readdir(join(cwd, '.pikacss/tmp'))
				.catch(() => [] as string[])
			return [...runDirTemps, ...tempDirTemps]
		}
		expect(await listTemps())
			.toEqual([])
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('color: red')

		// A failure during the temp write itself (partial temp on disk, then
		// an error) is cleaned up the same way: error propagates, no temp
		// residue, and the previous complete stylesheet stays in place.
		failNextTempWrite = true
		await expect(ctx.writeCssCodegenFile())
			.rejects
			.toThrow('temp write interrupted')
		expect(await listTemps())
			.toEqual([])
		expect(await readFile(ctx.cssCodegenFilepath, 'utf8'))
			.toContain('color: red')
	})

	it('swallows mkdir errors and still writes the generated file when the directory already exists', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'generated'), { recursive: true })

		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				mkdir: vi.fn()
					.mockRejectedValue(new Error('EACCES: permission denied')),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))
		// Pre-create the invocation-owned run directory and the temp directory
		// with the real mkdir (imported before the doMock), so only the
		// writer's own mkdir calls fail.
		await mkdir(dirname(ctx.cssCodegenFilepath), { recursive: true })
		await mkdir(join(cwd, '.pikacss/tmp'), { recursive: true })

		await ctx.setup()
		await ctx.writeCssCodegenFile()

		const content = await readFile(ctx.cssCodegenFilepath, 'utf-8')
		expect(content)
			.toContain('Auto-generated')
	})

	it('generates byte-identical CSS across full scans regardless of file creation order', async () => {
		// The two files mint different atomic ids depending on which one the
		// engine resolves first; path-sorted commit order makes it deterministic.
		const files: [string, string][] = [
			['src/a.ts', 'export const a = pika({ color: \'red\' })'],
			['src/z.ts', 'export const z = pika({ color: \'blue\' })'],
		]

		async function generate(order: 'forward' | 'reverse') {
			const cwd = await createTempDir()
			await mkdir(join(cwd, 'src'), { recursive: true })
			const ordered = order === 'forward' ? files : [...files].reverse()
			for (const [file, code] of ordered) {
				await writeFile(join(cwd, file), code)
			}

			const ctx = createCtx(createOptions({ cwd }))
			await withProcessCwd(cwd, async () => {
				await ctx.setup()
				await ctx.fullyCssCodegen()
			})
			return readFile(ctx.cssCodegenFilepath, 'utf8')
		}

		const first = await generate('forward')
		const second = await generate('forward')
		const reversed = await generate('reverse')

		expect(second)
			.toBe(first)
		expect(reversed)
			.toBe(first)
	})

	it('skips Vue SFC sub-requests carrying a vue&type= query', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const result = await ctx.transform(
			'export default { computed: { cls: () => pika({ color: \'red\' }) } }',
			join(cwd, 'src/App.vue?vue&type=script&lang.ts'),
		)
		expect(result)
			.toBeNull()
		expect(ctx.usages.size)
			.toBe(0)
	})

	it('reports scanned-but-not-transformed files until the bundler pass reaches them', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		const file = join(cwd, 'src/dead.ts')
		const code = 'export const a = pika({ color: \'red\' })'
		await writeFile(file, code)
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		await ctx.fullyCssCodegen()
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([file])

		// The bundler pass reaching the file clears it from the report.
		await ctx.transform(code, file)
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([])
	})

	it('clears canonical scanned-but-not-transformed diagnostics after the bundler transform reaches the source', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		const file = join(cwd, 'src/reached.ts')
		const code = `export const cls = pika({ color: 'red' })`
		await writeFile(file, code)
		await writeFile(join(cwd, 'pika.config.ts'), projectConfigSource(`
			export default defineConfig({ scan: { include: ['src/**/*.ts'], exclude: [] } })
		`))
		const ctx = createCtx(createOptions({ cwd, configOrPath: null }))
		await ctx.setup()

		await ctx.fullyCssCodegen()
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([file])
		await ctx.transform(code, file)
		expect(ctx.getScannedButNotTransformedFiles())
			.toEqual([])
		await ctx.waitForIdle()
	})

	it('drops usages keyed by the normalized path when dropModule receives a raw relative id', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)

		await ctx.transform('const a = pika({ color: \'red\' })', 'src/dropped.ts')
		const file = join(cwd, 'src/dropped.ts')
		expect(ctx.usages.has(file))
			.toBe(true)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		ctx.dropModule('src/dropped.ts')
		expect(ctx.usages.has(file))
			.toBe(false)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)
	})

	it('keeps the last-good usages when a re-transform of a previously good file rejects', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const file = join(cwd, 'src/last-good.ts')

		await ctx.transform('const a = pika({ color: \'red\' })', 'src/last-good.ts')
		const committed = ctx.usages.get(file)
		expect(committed)
			.toHaveLength(1)

		await expect(ctx.transform('const a = pika({ color: broken })', 'src/last-good.ts'))
			.rejects.toThrow(PikaTransformError)
		expect(ctx.usages.get(file))
			.toBe(committed)
	})

	it('serves a cache hit for identical (id, code) without extra engine work', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const useSpy = vi.spyOn(ctx.engine, 'prepareUse')

		const code = 'const a = pika({ color: \'red\' })'
		const first = await ctx.transform(code, 'src/cache-hit.ts')
		const callsAfterFirst = useSpy.mock.calls.length

		const second = await ctx.transform(code, 'src/cache-hit.ts')
		expect(useSpy.mock.calls.length)
			.toBe(callsAfterFirst)
		expect(second?.code)
			.toContain('\'pk-')
		expect(second?.code)
			.toBe(first?.code)
	})
})

describe('engine host context (#118)', () => {
	it('passes the effective project root to plugins as host.projectRoot', async () => {
		const cwd = await createTempDir()
		let observedRoot: string | undefined
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: {
				plugins: [{
					name: 'test:host-observer',
					configureEngine: (configurator: any) => {
						observedRoot = configurator.host.projectRoot
					},
				}],
			},
		}))
		await ctx.setup()

		// The integration's cwd — not process.cwd() — is the host authority.
		expect(observedRoot)
			.toBe(cwd)
	})
})
