/* eslint-disable no-template-curly-in-string */
import { describe, expect, it, vi } from 'vitest'

import { generateTsCodegenContent } from './tsCodegen'

function createStubContext(options?: {
	hasVue?: boolean
	transformedFormat?: 'string' | 'array'
}) {
	return {
		currentPackageName: '@pikacss/core',
		fnName: 'pika',
		hasVue: options?.hasVue ?? false,
		transformedFormat: options?.transformedFormat ?? 'string',
		usages: new Map([
			['src/demo.ts', [
				{ atomicStyleIds: ['pk-a'] },
				{ atomicStyleIds: ['pk-b'] },
			]],
		]),
		engine: {
			config: {
				autocomplete: {
					selectors: new Set(['hover']),
					shortcuts: new Set(['btn']),
					extraProperties: new Set(['__important']),
					extraCssProperties: new Set(['--brand']),
					properties: new Map([
						['__important', ['boolean']],
					]),
					cssProperties: new Map([
						['color', ['red']],
					]),
					patterns: {
						selectors: new Set(['/^child-(\\d+)$/']),
						shortcuts: new Set(['/^space-(\\d+)$/']),
						properties: new Map([
							['__important', ['true | false']],
						]),
						cssProperties: new Map([
							['color', ['/^var\\(--.+\\)$/']],
						]),
					},
				},
				layers: { components: 5, utilities: 10 },
			},
		},
	}
}

describe('generateTsCodegenContent', () => {
	it('renders autocomplete unions and Vue globals for array output mode', async () => {
		const ctx = createStubContext({
			hasVue: true,
			transformedFormat: 'array',
		})

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.toContain('// Auto-generated by @pikacss/core')
		expect(content)
			.toContain('declare module \'@pikacss/core\' {')
		expect(content)
			.toContain('Selector: "hover" | /^child-(\\d+)$/')
		expect(content)
			.toContain('Shortcut: "btn" | /^space-(\\d+)$/')
		expect(content)
			.toContain('PropertyValue: { "__important": boolean | true | false }')
		expect(content)
			.toContain('CSSPropertyValue: { "--brand": never, "color": "red" | /^var\\(--.+\\)$/ }')
		expect(content)
			.toContain('type StyleFn_Normal = StyleFn_Array')
		expect(content)
			.toContain('const pika: StyleFn')
		expect(content)
			.toContain('declare module \'vue\' {')
		// The preview surface is gone: no preview globals, overloads, or
		// usage-derived content of any kind (#113).
		expect(content)
			.not.toContain('Preview')
		expect(content)
			.not.toContain('pikap')
	})

	it('narrows governed properties when a strictTypes producer is present', async () => {
		const ctx = createStubContext()
		;(ctx.engine as any).designTokens = {
			strictTypes: () => [
				{ property: 'color', union: ['"var(--color-primary)"', '"inherit"', '`calc(${string})`'] },
				{ property: 'background-color', union: ['"var(--color-primary)"', '"inherit"'] },
				{ property: 'fill', union: [] },
			],
		}

		const content = await generateTsCodegenContent(ctx as any)

		// `PropertyValue` is imported only in strict mode.
		expect(content)
			.toContain('import type { CSSProperty, CSSSelector, Properties, StyleDefinition, StyleItem, PropertyValue } from \'@pikacss/core\'')
		expect(content)
			.toContain('type __PikaStrictProperties = {')
		expect(content)
			.toContain('"color"?: PropertyValue<"var(--color-primary)" | "inherit" | `calc(${string})`>')
		// A hyphenated property is emitted in both kebab and camel forms.
		expect(content)
			.toContain('"background-color"?: PropertyValue<"var(--color-primary)" | "inherit">')
		expect(content)
			.toContain('"backgroundColor"?: PropertyValue<"var(--color-primary)" | "inherit">')
		// An empty union renders as `never`.
		expect(content)
			.toContain('"fill"?: PropertyValue<never>')
		// The item type is intersected with the constraint.
		expect(content)
			.toContain('type StyleFn_String = (...params: (StyleItem & __PikaStrictProperties)[]) => string')
	})

	it('hoists large unions behind deduplicated aliases sharing a common tail', async () => {
		const ctx = createStubContext()
		// Two color properties share an identical (large) union; a dimension property
		// has a different large union with the same keyword/functional tail.
		const colorUnion = [
			'"var(--color-primary)"',
			'`var(--color-primary, ${string})`',
			'`var(${string}--color-primary${string})`',
			'"inherit"',
			'"initial"',
			'"unset"',
			'"revert"',
			'"revert-layer"',
			'"transparent"',
			'"currentColor"',
			'`calc(${string})`',
		]
		const dimUnion = [
			'"var(--space-sm)"',
			'`var(--space-sm, ${string})`',
			'`var(${string}--space-sm${string})`',
			'"inherit"',
			'"initial"',
			'"unset"',
			'"revert"',
			'"revert-layer"',
			'"0"',
			'"auto"',
			'`calc(${string})`',
		]
		;(ctx.engine as any).designTokens = {
			strictTypes: () => [
				{ property: 'color', union: colorUnion },
				{ property: 'background-color', union: colorUnion },
				{ property: 'padding', union: dimUnion },
			],
		}

		const content = await generateTsCodegenContent(ctx as any)

		// The tail common to every hoisted union is factored into one shared alias.
		expect(content)
			.toContain('type __PikaStrictShared = "inherit" | "initial" | "unset" | "revert" | "revert-layer" | `calc(${string})`')

		// Each governed property references a named alias, not an inline union.
		const aliasFor = (property: string): string => {
			const match = content.match(new RegExp(`${property}"\\?: PropertyValue<(__PikaStrict\\d+)>`))
			expect(match, `expected an aliased value for "${property}"`)
				.not.toBeNull()
			return match![1]!
		}
		// Same-union properties (color + background-color) and the camel form all
		// share one alias; the dimension property gets a distinct one.
		const colorAlias = aliasFor('"color')
		expect(aliasFor('"background-color'))
			.toBe(colorAlias)
		expect(aliasFor('"backgroundColor'))
			.toBe(colorAlias)
		expect(aliasFor('"padding'))
			.not.toBe(colorAlias)

		// Alias bodies carry only their type-specific members plus the shared tail.
		expect(content)
			.toContain(`type ${colorAlias} = "var(--color-primary)" | \`var(--color-primary, \${string})\` | \`var(\${string}--color-primary\${string})\` | "transparent" | "currentColor" | __PikaStrictShared`)
		expect(content)
			.toContain('| "0" | "auto" | __PikaStrictShared')
		// The color alias never carries the dimension allowlist, and vice versa.
		expect(content)
			.not.toContain(`type ${colorAlias} = "var(--color-primary)" | \`var(--color-primary, \${string})\` | \`var(\${string}--color-primary\${string})\` | "0"`)
	})

	it('emits byte-identical style-fn types and import when no strictTypes producer is present', async () => {
		const ctx = createStubContext()

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.not.toContain('__PikaStrictProperties')
		expect(content)
			.toContain('import type { CSSProperty, CSSSelector, Properties, StyleDefinition, StyleItem } from \'@pikacss/core\'')
		expect(content)
			.toContain('type StyleFn_String = (...params: StyleItem[]) => string')
	})

	it('ignores a malformed strictTypes producer', async () => {
		const ctx = createStubContext()
		;(ctx.engine as any).designTokens = { strictTypes: () => 'not-an-array' }

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.not.toContain('__PikaStrictProperties')
		expect(content)
			.toContain('type StyleFn_String = (...params: StyleItem[]) => string')
	})

	it('falls back to never unions and omits Vue declarations when no autocomplete data exists', async () => {
		const ctx = {
			currentPackageName: '@pikacss/core',
			fnName: 'pika',
			hasVue: false,
			transformedFormat: 'string',
			usages: new Map(),
			engine: {
				config: {
					autocomplete: {
						selectors: new Set(),
						shortcuts: new Set(),
						extraProperties: new Set(),
						extraCssProperties: new Set(),
						properties: new Map(),
						cssProperties: new Map(),
					},
					layers: {},
				},
				renderAtomicStyles: vi.fn(),
			},
		}

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.toContain('type StyleFn_Normal = StyleFn_String')
		expect(content)
			.toContain('Selector: never')
		expect(content)
			.toContain('Shortcut: never')
		expect(content)
			.toContain('PropertyValue: never')
		expect(content)
			.toContain('CSSPropertyValue: never')
		expect(content)
			.toContain('Layer: never')
		expect(content.includes('declare module \'vue\' {'))
			.toBe(false)
	})

	it('omits the normal style alias when transformedFormat is outside supported runtime values', async () => {
		const ctx = {
			currentPackageName: '@pikacss/core',
			fnName: 'pika',
			hasVue: false,
			transformedFormat: 'other',
			usages: new Map(),
			engine: {
				config: {
					autocomplete: {
						selectors: new Set(),
						shortcuts: new Set(),
						extraProperties: new Set(),
						extraCssProperties: new Set(),
						properties: new Map(),
						cssProperties: new Map(),
						patterns: undefined,
					},
					layers: {},
				},
				renderAtomicStyles: vi.fn(),
			},
		}

		const content = await generateTsCodegenContent(ctx as any)

		expect(content.includes('type StyleFn_Normal = StyleFn_Array'))
			.toBe(false)
		expect(content.includes('type StyleFn_Normal = StyleFn_String'))
			.toBe(false)
	})
})
