import { describe, expect, it } from 'vitest'

import { renderTsCodegenContent } from './tsCodegen'

describe('renderTsCodegenContent', () => {
	it('renders only the captured Engine Typegen snapshot and binding metadata', () => {
		const content = renderTsCodegenContent({
			snapshot: Object.freeze({
				previewAssets: Object.freeze([]),
				contributions: Object.freeze([Object.freeze({
					id: 'test:types',
					declarations: 'interface __TestMarker { readonly marker: true }',
					pika: Object.freeze({ marker: '__TestMarker' }),
				})]),
			}),
			fnName: 'customPika',
			transformedFormat: 'array',
			publicModule: '@pikacss/core',
		})

		expect(content)
			.toContain('// Auto-generated by PikaCSS')
		expect(content)
			.toContain('interface __TestMarker { readonly marker: true }')
		expect(content)
			.toContain('type __StyleFn = (...params: __StyleItem[]) => string[]')
		expect(content)
			.toContain('\"marker\": __TestMarker')
		expect(content)
			.toContain('const customPika: __PikaTypegenUnit0.Pika')
		expect(content)
			.not.toContain('Preview')
		expect(content)
			.not.toContain('.str')
		expect(content)
			.not.toContain('.arr')
	})
})
