import { describe, expect, it } from 'vitest'

import { generateTsCodegenContent } from './tsCodegen'

function createStubContext(options?: {
	hasVue?: boolean
	transformedFormat?: 'string' | 'array'
}) {
	return {
		currentPackageName: '@pikacss/core',
		fnName: 'pika',
		hasVue: options?.hasVue ?? false,
		transformedFormat: options?.transformedFormat ?? 'string',
		usages: new Map([
			['src/demo.ts', [
				{ atomicStyleIds: ['pk-a'] },
				{ atomicStyleIds: ['pk-b'] },
			]],
		]),
		engine: {
			config: {
				autocomplete: {
					selectors: new Set(['hover']),
					shortcuts: new Set(['btn']),
					extraProperties: new Set(['__important']),
					extraCssProperties: new Set(['--brand']),
					properties: new Map([
						['__important', ['boolean']],
					]),
					cssProperties: new Map([
						['color', ['red']],
					]),
					patterns: {
						selectors: new Set(['/^child-(\\d+)$/']),
						shortcuts: new Set(['/^space-(\\d+)$/']),
						properties: new Map([
							['__important', ['true | false']],
						]),
						cssProperties: new Map([
							['color', ['/^var\\(--.+\\)$/']],
						]),
					},
				},
				layers: { components: 5, utilities: 10 },
			},
		},
	}
}

describe('generateTsCodegenContent', () => {
	it('renders autocomplete unions and Vue globals for array output mode', async () => {
		const ctx = createStubContext({
			hasVue: true,
			transformedFormat: 'array',
		})

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.toContain('// Auto-generated by @pikacss/core')
		expect(content)
			.toContain('declare module \'@pikacss/core\' {')
		expect(content)
			.toContain('Selector: "hover" | /^child-(\\d+)$/')
		expect(content)
			.toContain('Shortcut: "btn" | /^space-(\\d+)$/')
		expect(content)
			.toContain('PropertyValue: { "__important": boolean | true | false }')
		expect(content)
			.toContain('CSSPropertyValue: { "--brand": never, "color": "red" | /^var\\(--.+\\)$/ }')
		expect(content)
			.toContain('type StyleFn_Normal = StyleFn_Array')
		expect(content)
			.toContain('const pika: StyleFn')
		expect(content)
			.toContain('declare module \'vue\' {')
		// The preview surface is gone: no preview globals, overloads, or
		// usage-derived content of any kind (#113).
		expect(content)
			.not.toContain('Preview')
		expect(content)
			.not.toContain('pikap')
	})
})
