import type { DiagnosticHandler, Engine, EngineConfig, Nullish } from '@pikacss/core'
import type { SourceMap } from 'magic-string'
import type { createEventHook } from './eventHook'

/**
 * Records a single `pika()` call result: the resolved atomic style IDs.
 *
 * @remarks
 * Each source file may produce multiple `UsageRecord` entries — one per `pika()` call site.
 * These records drive CSS output only; generated TypeScript declarations are a
 * projection of the effective project/type configuration and never read them.
 */
export interface UsageRecord {
	/** The list of atomic CSS class names generated by the engine for this call. */
	atomicStyleIds: string[]
}

/**
 * Configuration options for creating an integration context.
 *
 * @remarks
 * These options are set by bundler plugin adapters (Vite, webpack, Nuxt) and are
 * not typically configured by end users directly.
 */
export interface IntegrationContextOptions {
	/** The working directory used to resolve relative paths for config files, codegen outputs, and source scanning. */
	cwd: string
	/** The npm package name of the integration consumer (e.g., `'@pikacss/unplugin-pikacss'`), embedded in generated file headers and import paths. */
	currentPackageName: string
	/** Glob patterns controlling which source files are scanned for `pika()` calls. `include` specifies files to process; `exclude` specifies files to skip. */
	scan: {
		include: string[]
		exclude: string[]
	}
	/** The engine configuration object, a path to a config file, or `null`/`undefined` to trigger auto-discovery of `pika.config.*` files. */
	configOrPath: EngineConfig | string | Nullish
	/** The reserved compile-time base function identifier recognized in source code (e.g. `'pika'`). */
	fnName: string
	/** Controls the default output format of normal `pika()` calls: `'string'` produces a space-joined class string, `'array'` produces a string array. */
	transformedFormat: 'string' | 'array'
	/** Path to the generated TypeScript declaration file (`pika.gen.ts`), or `false` to disable TypeScript codegen entirely. */
	tsCodegen: false | string
	/** When `true`, automatically scaffolds a default `pika.config.js` file if no config file is found. */
	autoCreateConfig: boolean
	/** Receives engine diagnostics. Defaults to the official console adapter. */
	onDiagnostic?: DiagnosticHandler
}

/**
 * Discriminated union representing the outcome of loading an engine configuration file.
 *
 * @remarks
 * Four shapes are possible: an inline config (no file), a successfully loaded file-based
 * config, a file that exists but failed to evaluate (path and content kept so integrations
 * can watch it and reload after a fix), or a missing load (all fields `null`). The `file`
 * and `content` fields are populated whenever the config file was found on disk, enabling
 * hot-reload detection.
 */
export type LoadedConfigResult
	= | { config: EngineConfig, file: null, content: null }
		| { config: null, file: null, content: null }
		| { config: EngineConfig, file: string, content: string }
		| { config: null, file: string, content: string }

/**
 * The main build-tool integration context that bridges the PikaCSS engine with bundler plugins.
 *
 * @remarks
 * Created via `createCtx()`. The context manages the full build lifecycle: config loading,
 * engine initialization, source file transformation, usage tracking, and output file generation.
 * All transform and codegen calls automatically await `setup()` completion before proceeding.
 */
export interface IntegrationContext {
	/** The current working directory. Can be updated at runtime (e.g., when the project root changes). */
	cwd: string
	/**
	 * How the context reacts to a config file that fails to evaluate or an engine
	 * that fails to build. Set by the bundler adapter from the build mode.
	 *
	 * @remarks
	 * `'throw'` (build) rejects `setup()` so the bundler fails the build loudly
	 * instead of emitting CSS from a silently-empty config. `'retain-last-good'`
	 * (dev) keeps the process alive: it retains the previous engine and all
	 * collected usages when one exists, or boots a plugin-only default engine on
	 * the very first setup. Defaults to `'retain-last-good'`.
	 */
	configErrorBehavior: 'throw' | 'retain-last-good'
	/** The npm package name of the integration consumer, used in generated file headers and module declarations. */
	currentPackageName: string
	/** The base function name recognized in source transforms (e.g., `'pika'`). */
	fnName: string
	/** The default output format for normal `pika()` calls: `'string'` or `'array'`. */
	transformedFormat: 'string' | 'array'
	/** Absolute path to this invocation's physical runtime CSS file under `<cwd>/.pikacss/runs/<run-id>/pika.css`. Invocation-owned internal state — not user-configurable. */
	cssCodegenFilepath: string
	/** Absolute path to the generated TypeScript declaration file, or `null` if TypeScript codegen is disabled. */
	tsCodegenFilepath: string | Nullish
	/** Whether the `vue` package is installed in the project, used to include Vue-specific type declarations in codegen. */
	hasVue: boolean
	/** The loaded engine configuration object, or `null` if loading failed or no config was found. */
	resolvedConfig: EngineConfig | Nullish
	/** Absolute path to the resolved config file on disk, or `null` for inline configs or when no config was loaded. */
	resolvedConfigPath: string | Nullish
	/** Raw string content of the config file, or `null` for inline configs or when no config was loaded. */
	resolvedConfigContent: string | Nullish
	/** Loads (or reloads) the engine configuration from disk or inline source, updating `resolvedConfig`, `resolvedConfigPath`, and `resolvedConfigContent`. */
	loadConfig: () => Promise<LoadedConfigResult>
	/** Map from source file ID to the list of `UsageRecord` entries extracted during transforms. Keyed by the normalized absolute file path (`parseModuleId(...).file`). */
	usages: Map<string, UsageRecord[]>
	/** Event hooks for notifying plugins when generated outputs need refreshing. `styleUpdated` fires on CSS changes; `tsCodegenUpdated` fires on TypeScript declaration changes. */
	hooks: {
		styleUpdated: ReturnType<typeof createEventHook<void>>
		tsCodegenUpdated: ReturnType<typeof createEventHook<void>>
		/** Fires with the absolute path of each config dependency registered after engine setup (#122), so bundler adapters can extend the active watcher dynamically. */
		dependencyAdded: ReturnType<typeof createEventHook<string>>
	}
	/** The initialized PikaCSS engine instance. Throws if accessed before `setup()` completes. */
	engine: Engine
	/**
	 * Glob patterns for the bundler's transform pipeline, derived from the scan config with codegen files excluded.
	 *
	 * @remarks
	 * Bundler plugin adapters may read these patterns once at plugin conversion and resolve
	 * relative patterns against `process.cwd()` before `cwd` is finalized, so the
	 * cwd-relative excludes are only a best effort. Re-check candidate ids at transform
	 * time via {@link IntegrationContext.isTransformTarget}.
	 */
	transformFilter: {
		include: string[]
		exclude: string[]
	}
	/**
	 * Returns whether a module id should be transformed, evaluated against the CURRENT `cwd`.
	 *
	 * @param id - A module id (absolute or `cwd`-relative file path; query/hash suffixes such as `?vue&type=script` are ignored).
	 * @returns `true` when the id matches `scan.include`, does not match `scan.exclude`, and is not one of the codegen output files.
	 *
	 * @remarks
	 * Unlike `transformFilter`, this predicate resolves relative ids and relative scan
	 * patterns against the current `cwd` at call time and always rejects the CSS/TS
	 * codegen output filepaths, so bundler adapters should call it per id at transform
	 * time instead of relying solely on the declarative filter.
	 */
	isTransformTarget: (id: string) => boolean
	/**
	 * Whether no `transform()` calls are currently in flight.
	 *
	 * @remarks
	 * Only actual transform work is counted: a `transform()` call that is still awaiting
	 * `setupPromise` or resolves from the internal result cache never marks the context busy.
	 * Use this for synchronous decisions (e.g. defer generated-file writes while busy) and
	 * {@link IntegrationContext.waitForIdle} to asynchronously await idleness.
	 */
	readonly isIdle: boolean
	/**
	 * Resolves once all in-flight `transform()` calls have settled.
	 *
	 * @returns A promise that resolves when no transforms are in flight; resolves immediately when the context is already idle.
	 *
	 * @remarks
	 * Resolution only guarantees the transforms that were active at call time have finished;
	 * new transforms may start afterwards. `setup()` uses the same mechanism internally to
	 * drain in-flight transforms before swapping the engine.
	 */
	waitForIdle: () => Promise<void>
	/**
	 * Processes a source file by extracting `pika()` calls via the AST compiler, resolving them
	 * through the engine, and replacing them with computed output.
	 *
	 * @returns The transformed code and source map, or `null` when the module has no macro calls
	 * or is filtered out (unsupported extension, fn-name substring absent, Vue SFC sub-request).
	 * @throws `PikaTransformError` when any call in the module fails to parse, resolve, or
	 * statically evaluate — module transforms are atomic and never commit partial results; the
	 * module's previously committed usages stay intact (last-good).
	 */
	transform: (code: string, id: string) => Promise<{ code: string, map: SourceMap } | Nullish>
	/**
	 * Drops all state for a module (usages, prepared results), e.g. when the
	 * bundler reports the file as deleted. Accepts raw bundler ids (relative paths, query/hash
	 * suffixes) and normalizes them internally. Queues output regeneration when styles were dropped.
	 */
	dropModule: (id: string) => void
	/**
	 * Returns the physical files whose styles entered the generated CSS during the build-mode
	 * full scan but that the bundler's own transform pass never reached — dead files or files
	 * missing from the import graph. Sorted; empty in dev mode (no full scan).
	 */
	getScannedButNotTransformedFiles: () => string[]
	/** Generates the full CSS output string, including layer declarations, preflights, and all atomic styles collected from transforms. */
	getCssCodegenContent: () => Promise<string | Nullish>
	/** Generates the full TypeScript declaration content for `pika.gen.ts`, or `null` if TypeScript codegen is disabled. */
	getTsCodegenContent: () => Promise<string | Nullish>
	/** Generates and writes the runtime CSS to `cssCodegenFilepath`. Byte-identical content skips the write; changed content is replaced atomically via a unique same-directory temporary file. */
	writeCssCodegenFile: () => Promise<void>
	/** Generates and writes the TypeScript codegen file to disk at `tsCodegenFilepath`. No-op if TypeScript codegen is disabled. */
	writeTsCodegenFile: () => Promise<void>
	/** Scans all matching source files, collects usages via transform, then writes the CSS codegen file. Used for full rebuilds. */
	fullyCssCodegen: () => Promise<void>
	/** The pending setup promise while initialization is in progress, or `null` when idle. Transform calls await this before proceeding. */
	setupPromise: Promise<void> | null
	/** Initializes (or reinitializes) the context by clearing state, loading config, creating the engine, and wiring up dev hooks. Returns a promise that resolves when setup is complete. */
	setup: () => Promise<void>
}
