// Auto-generated by @styocss/vite-plugin-styocss
import type { StyleFn } from '@styocss/vite-plugin-styocss'

interface _Autocomplete {
	Selector: '@dark'
	StyleItemString: never
	ExtraProperty: '$important' | '$apply'
	ExtraCssProperty: never
	PropertiesValue: { $important: boolean, $apply: never | never }
	CssPropertiesValue: { animationName: never, animation: never }
}

type _StyleFn = StyleFn<_Autocomplete>

type StyleFn_Normal = StyleFn_String
type StyleFn_Array = (...params: Parameters<_StyleFn>) => string[]
type StyleFn_String = (...params: Parameters<_StyleFn>) => string
type StyleFn_Inline = (...params: Parameters<_StyleFn>) => void

type Styo = StyleFn_Normal & {
	str: StyleFn_String
	arr: StyleFn_Array
	inl: StyleFn_Inline
}
type StyoWithPreview = PreviewOverloads<StyleFn_Normal>['fn'] & {
	str: PreviewOverloads<StyleFn_String>['fn']
	arr: PreviewOverloads<StyleFn_Array>['fn']
	inl: PreviewOverloads<StyleFn_Inline>['fn']
}

declare global {
	/**
	 * StyoCSS
	 */
	const styo: Styo

	/**
	 * StyoCSS Preview
	 */
	const styop: StyoWithPreview
}

declare module 'vue' {
	interface ComponentCustomProperties {
		/**
		 * StyoCSS
		 */
		styo: Styo

		/**
		 * StyoCSS Preview
		 */
		styop: StyoWithPreview
	}
}

interface PreviewOverloads<StyleFn extends (StyleFn_Array | StyleFn_String | StyleFn_Inline)> {
	/**
	 * StyoCSS Preview
	 * Save the current file to see the preview.
	 */
	fn: (...params: Parameters<StyleFn>) => ReturnType<StyleFn>
}
