const ATOMIC_STYLE_NAME_PLACEHOLDER = '$'
const ATOMIC_STYLE_NAME_PLACEHOLDER_RE_GLOBAL = /\$/g
const DEFAULT_SELECTOR_PLACEHOLDER = '$$'
const DEFAULT_SELECTOR_PLACEHOLDER_RE_GLOBAL = /\$\$/g

export {
	ATOMIC_STYLE_NAME_PLACEHOLDER,
	ATOMIC_STYLE_NAME_PLACEHOLDER_RE_GLOBAL,
	DEFAULT_SELECTOR_PLACEHOLDER,
	DEFAULT_SELECTOR_PLACEHOLDER_RE_GLOBAL,
}
