import type { PackageDef } from '../_skill-shared'
import { writeFileSync } from 'node:fs'
import process from 'node:process'
import { join } from 'pathe'
import ts from 'typescript'
import { PACKAGES, workspaceRoot } from '../_skill-shared'
import { hasInternalJsDocTag, isPrivateOrProtectedDeclaration, selectFunctionApiDeclarations } from './api-helpers'

const ROOT = workspaceRoot
const RE_TRAILING_INLINE_WHITESPACE = /[ \t]+\n/g
const RE_TRAILING_PARAM_SEPARATOR = /^\s*-?\s*/
const RE_NUMERIC_LITERAL_TEXT = /^-?\d/
const RE_TABLE_PIPE = /\|/g
const RE_NEWLINE = /\n/g
const RE_COMBINING_MARKS = /[\u0300-\u036F]/g
const RE_SLUG_PUNCTUATION = /[\s~`!@#$%^&*()\-_+=[\]{}|\\;:"'<>,.?/]+/g
const RE_REPEATED_DASH = /-{2,}/g
const RE_TRIM_DASH = /^-|-$/g
const RE_LEADING_DIGIT = /^(\d)/
const RE_VALID_PARAM_PATH_SEGMENT = /^[A-Z_$][\w$]*$/i

interface ParamInfo {
	name: string
	type: string
	description: string
	optional: boolean
}

interface MemberInfo {
	name: string
	type: string
	description: string
	optional: boolean
	defaultValue?: string
}

interface FunctionSignatureInfo {
	description: string
	params: ParamInfo[]
	returnType?: string
	returnsDescription?: string
	typeParams?: { name: string, description: string }[]
	remarks?: string
	examples?: string[]
}

interface ExportInfo {
	name: string
	kind: 'function' | 'interface' | 'type' | 'const' | 'class' | 'unknown'
	typeOnly: boolean
	internal?: boolean
	description: string
	params?: ParamInfo[]
	returnType?: string
	returnsDescription?: string
	typeParams?: { name: string, description: string }[]
	remarks?: string
	examples?: string[]
	defaultValue?: string
	resolvedType?: string
	members?: MemberInfo[]
	methods?: MethodInfo[]
	signatures?: FunctionSignatureInfo[]
}

interface MethodInfo {
	name: string
	description: string
	params: ParamInfo[]
	returnType?: string
	returnsDescription?: string
	typeParams?: { name: string, description: string }[]
}

interface AugmentationInfo {
	moduleName: string
	interfaceName: string
	members: MemberInfo[]
}

interface PackageAPIInfo {
	pkg: PackageDef
	exports: ExportInfo[]
	augmentations: AugmentationInfo[]
	relatedSources: string[]
}

interface CoverageGap {
	subject: string
	missing: string[]
}

interface Locale {
	generatedNote: string
	packageSummary: string
	functions: string
	types: string
	constants: string
	moduleAugmentations: string
	paramCol: string
	typeCol: string
	descCol: string
	defaultCol: string
	propertyCol: string
	classes: string
	methods: string
	returns: string
	typeParams: string
	remarks: string
	reExports: string
	missingSummary: string
	kindLabels: Record<ExportInfo['kind'], string>
	sourceInfoSummary: string
	overviewLink: { text: string, url: string }
	sourceIntro: string
	sourceFilesLabel: string
	generatedDescription: (pkg: PackageDef) => string
	typeOnlyNote: (pkg: PackageDef) => string
	internalNote: string
}

const EN: Locale = {
	generatedNote: '<!-- AUTO-GENERATED by scripts/maintain-docs/gen-api-docs.ts — do not edit manually -->',
	packageSummary: 'Package summary',
	functions: 'Functions',
	types: 'Types',
	constants: 'Constants',
	classes: 'Classes',
	methods: 'Methods',
	moduleAugmentations: 'Module augmentations',
	paramCol: 'Parameter',
	typeCol: 'Type',
	descCol: 'Description',
	defaultCol: 'Default',
	propertyCol: 'Property',
	returns: 'Returns',
	typeParams: 'Type parameters',
	remarks: 'Remarks',
	reExports: 'Re-exports the public surface of',
	missingSummary: 'Missing JSDoc summary.',
	kindLabels: {
		function: 'Function',
		const: 'Constant',
		class: 'Class',
		interface: 'Interface',
		type: 'Type',
		unknown: 'Export',
	},
	sourceInfoSummary: 'Source information',
	overviewLink: { text: 'API reference overview', url: '/api/' },
	sourceIntro: 'Generated from the exported surface and JSDoc in',
	sourceFilesLabel: 'Source files',
	generatedDescription: pkg => `Generated API reference for ${pkg.name} from exported surface and JSDoc.`,
	typeOnlyNote: pkg => `**Type-only export.** This symbol is exported with \`export type\` and is not a runtime export of \`${pkg.name}\` — importing it as a value will fail. It is documented here for its type signature only.`,
	internalNote: '**Internal API.** Tagged `@internal` in the source: exported at runtime, but intended for PikaCSS\'s own packages and may change without notice.',
}

function createApiProgram(): ts.Program {
	const entries = PACKAGES.map(pkg => join(ROOT, 'packages', pkg.dir, 'src/index.ts'))
	const pathsMappings: Record<string, string[]> = {}

	for (const pkg of PACKAGES) {
		pathsMappings[pkg.name] = [join(ROOT, 'packages', pkg.dir, 'src/index.ts')]
		pathsMappings[`${pkg.name}/*`] = [join(ROOT, 'packages', pkg.dir, 'src/*')]
	}

	return ts.createProgram(entries, {
		target: ts.ScriptTarget.ESNext,
		module: ts.ModuleKind.ESNext,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		strict: true,
		skipLibCheck: true,
		noEmit: true,
		esModuleInterop: true,
		baseUrl: ROOT,
		paths: pathsMappings,
	})
}

function normalizeDocsText(text: string): string {
	const replacements = [
		['Engine.useuse', 'Engine.use'],
		['Engine.renderPreflightsrenderPreflights', 'Engine.renderPreflights'],
		['Engine.renderAtomicStylesrenderAtomicStyles', 'Engine.renderAtomicStyles'],
		['Engine.renderLayerOrderDeclarationrenderLayerOrderDeclaration', 'Engine.renderLayerOrderDeclaration'],
		['Engine.addPreflightaddPreflight', 'Engine.addPreflight'],
		['Engine.appendAutocompleteappendAutocomplete', 'Engine.appendAutocomplete'],
		['Engine.appendCssImportappendCssImport', 'Engine.appendCssImport'],
		['IntegrationContext.setupctx.setup', 'IntegrationContext.setup'],
		['IntegrationContext.setupsetup', 'IntegrationContext.setup'],
		['PluginOptions.autoCreateConfigautoCreateConfig', 'PluginOptions.autoCreateConfig'],
		['PluginOptions.tsCodegentsCodegen', 'PluginOptions.tsCodegen'],
	] as const

	let normalized = normalizeLinkTags(text)
		.replace(RE_TRAILING_INLINE_WHITESPACE, '\n')
		.trim()
	for (const [from, to] of replacements)
		normalized = normalized.replaceAll(from, to)

	return normalized
}

function normalizeLinkTags(text: string): string {
	let normalized = text

	while (true) {
		const start = normalized.indexOf('{@link')
		if (start === -1)
			return normalized

		const end = normalized.indexOf('}', start)
		if (end === -1)
			return normalized

		const body = normalized.slice(start + 6, end)
			.trim()
		const labelIndex = body.indexOf('|')
		const replacement = labelIndex === -1
			? body.trim()
			: body.slice(labelIndex + 1)
					.trim()

		normalized = `${normalized.slice(0, start)}${replacement}${normalized.slice(end + 1)}`
	}
}

function getSymbolDescription(sym: ts.Symbol, checker: ts.TypeChecker): string {
	return normalizeDocsText(
		ts.displayPartsToString(sym.getDocumentationComment(checker))
			.trim(),
	)
}

function getTagText(tag: ts.JSDocTagInfo): string {
	return normalizeDocsText(
		tag.text
			? ts.displayPartsToString(tag.text)
					.trim()
			: '',
	)
}

function getParamDescription(tags: ts.JSDocTagInfo[], paramName: string): string {
	const tag = tags.find(entry => entry.name === 'param' && entry.text?.some(part => part.kind === 'parameterName' && part.text === paramName))
	if (!tag?.text)
		return ''

	const nameIndex = tag.text.findIndex(part => part.kind === 'parameterName')
	if (nameIndex === -1)
		return ''

	return normalizeDocsText(
		tag.text.slice(nameIndex + 1)
			.map(part => part.text)
			.join('')
			.replace(RE_TRAILING_PARAM_SEPARATOR, ''),
	)
}

function appendParamPath(baseName: string, propertyName: string): string {
	return RE_VALID_PARAM_PATH_SEGMENT.test(propertyName)
		? `${baseName}.${propertyName}`
		: `${baseName}[${JSON.stringify(propertyName)}]`
}

function getBindingElementPropertyName(element: ts.BindingElement): string {
	if (element.propertyName) {
		if (ts.isIdentifier(element.propertyName) || ts.isStringLiteral(element.propertyName) || ts.isNumericLiteral(element.propertyName))
			return element.propertyName.text
		return element.propertyName.getText()
	}

	if (ts.isIdentifier(element.name))
		return element.name.text

	return element.name.getText()
}

function getSyntheticParamName(name: ts.BindingName, index: number): string {
	if (ts.isObjectBindingPattern(name))
		return index === 0 ? 'options' : `options${index + 1}`

	if (ts.isArrayBindingPattern(name))
		return index === 0 ? 'items' : `items${index + 1}`

	return name.getText()
}

function isOptionalSymbol(symbol: ts.Symbol | undefined): boolean {
	return Boolean(symbol && (symbol.getFlags() & ts.SymbolFlags.Optional))
}

function buildParamInfoList(parameters: readonly ts.ParameterDeclaration[], tags: ts.JSDocTagInfo[], checker: ts.TypeChecker): ParamInfo[] {
	const params: ParamInfo[] = []

	parameters.forEach((param, index) => {
		const name = getSyntheticParamName(param.name, index)
		const type = param.type?.getText() || checker.typeToString(checker.getTypeAtLocation(param)) || 'unknown'
		params.push({
			name,
			type,
			description: getParamDescription(tags, name),
			optional: !!(param.questionToken || param.initializer),
		})

		if (ts.isObjectBindingPattern(param.name)) {
			params.push(...collectObjectBindingParamInfo(param.name, name, checker.getTypeAtLocation(param), tags, checker))
		}
	})

	return params
}

function collectObjectBindingParamInfo(
	pattern: ts.ObjectBindingPattern,
	baseName: string,
	parentType: ts.Type,
	tags: ts.JSDocTagInfo[],
	checker: ts.TypeChecker,
): ParamInfo[] {
	const params: ParamInfo[] = []

	for (const element of pattern.elements) {
		const propertyName = getBindingElementPropertyName(element)
		const name = appendParamPath(baseName, propertyName)
		const propertySymbol = parentType.getProperty(propertyName)
		const propertyType = propertySymbol
			? checker.getTypeOfSymbolAtLocation(propertySymbol, element)
			: undefined

		params.push({
			name,
			type: propertyType ? checker.typeToString(propertyType) : 'unknown',
			description: getParamDescription(tags, name),
			optional: !!element.initializer || isOptionalSymbol(propertySymbol),
		})

		if (propertyType && ts.isObjectBindingPattern(element.name))
			params.push(...collectObjectBindingParamInfo(element.name, name, propertyType, tags, checker))
	}

	return params
}

function getTypeParamDescriptions(tags: ts.JSDocTagInfo[]): { name: string, description: string }[] {
	return tags
		.filter(tag => tag.name === 'typeParam')
		.map((tag) => {
			const parts = tag.text || []
			const nameIndex = parts.findIndex(part => part.kind === 'typeParameterName')
			if (nameIndex === -1)
				return { name: '', description: '' }
			const namePart = parts[nameIndex]
			if (!namePart)
				return { name: '', description: '' }

			return {
				name: namePart.text,
				description: normalizeDocsText(
					parts.slice(nameIndex + 1)
						.map(part => part.text)
						.join('')
						.replace(RE_TRAILING_PARAM_SEPARATOR, ''),
				),
			}
		})
		.filter(typeParam => typeParam.name)
}

function getTagByName(tags: ts.JSDocTagInfo[], name: string): string | undefined {
	const tag = tags.find(entry => entry.name === name)
	return tag ? getTagText(tag) : undefined
}

function getExamples(tags: ts.JSDocTagInfo[]): string[] {
	return tags
		.filter(tag => tag.name === 'example')
		.map(getTagText)
		.filter(Boolean)
}

function isOwnDeclaration(decl: ts.Declaration, pkgDir: string): boolean {
	return decl.getSourceFile().fileName.includes(`/packages/${pkgDir}/`)
}

function collectOwnSourcePaths(sym: ts.Symbol, pkgDir: string): string[] {
	const declarations = sym.getDeclarations() ?? []
	const paths = declarations
		.filter(decl => isOwnDeclaration(decl, pkgDir))
		.map((decl) => {
			const filePath = decl.getSourceFile().fileName
			return filePath.startsWith(`${ROOT}/`) ? filePath.slice(ROOT.length + 1) : filePath
		})

	return [...new Set(paths)].sort()
}

function resolveExportedSymbol(sym: ts.Symbol, checker: ts.TypeChecker): ts.Symbol {
	if ((sym.flags & ts.SymbolFlags.Alias) !== 0) {
		try {
			return checker.getAliasedSymbol(sym)
		}
		catch {
			return sym
		}
	}

	return sym
}

/**
 * Collects the export names of a module that are usable as runtime values.
 *
 * Walks the module's export statements so that `export type { ... }`,
 * per-specifier `type` modifiers, and `export type * from '...'` are all
 * excluded — the TypeScript checker alone cannot distinguish those from value
 * re-exports once aliases are resolved. Star value re-exports recurse into the
 * target module so type-only exports never pass through a value star export.
 */
function collectValueExportNames(sourceFile: ts.SourceFile, checker: ts.TypeChecker, cache: Map<string, Set<string>>): Set<string> {
	const cached = cache.get(sourceFile.fileName)
	if (cached)
		return cached

	const names = new Set<string>()
	// Register before walking so circular re-export chains terminate.
	cache.set(sourceFile.fileName, names)

	for (const stmt of sourceFile.statements) {
		if (ts.isExportAssignment(stmt)) {
			names.add('default')
			continue
		}

		if (ts.isExportDeclaration(stmt)) {
			if (stmt.isTypeOnly)
				continue

			if (stmt.exportClause && ts.isNamedExports(stmt.exportClause)) {
				for (const spec of stmt.exportClause.elements) {
					if (!spec.isTypeOnly)
						names.add(spec.name.text)
				}
				continue
			}

			if (stmt.exportClause && ts.isNamespaceExport(stmt.exportClause)) {
				names.add(stmt.exportClause.name.text)
				continue
			}

			// `export * from '...'`: only names the target module exports as values pass through.
			const targetSymbol = stmt.moduleSpecifier ? checker.getSymbolAtLocation(stmt.moduleSpecifier) : undefined
			if (!targetSymbol)
				continue
			const targetSourceFile = targetSymbol.getDeclarations()
				?.find(ts.isSourceFile)
			if (targetSourceFile) {
				// `export *` never re-exports the target's default export.
				for (const name of collectValueExportNames(targetSourceFile, checker, cache)) {
					if (name !== 'default')
						names.add(name)
				}
			}
			else {
				for (const exported of checker.getExportsOfModule(targetSymbol)) {
					if ((resolveExportedSymbol(exported, checker).flags & ts.SymbolFlags.Value) !== 0)
						names.add(exported.getName())
				}
			}
			continue
		}

		if (!ts.canHaveModifiers(stmt))
			continue
		const modifiers = ts.getModifiers(stmt) ?? []
		if (!modifiers.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword))
			continue
		const isDefault = modifiers.some(modifier => modifier.kind === ts.SyntaxKind.DefaultKeyword)

		if (ts.isVariableStatement(stmt)) {
			for (const decl of stmt.declarationList.declarations) {
				if (ts.isIdentifier(decl.name))
					names.add(decl.name.text)
			}
		}
		else if (ts.isFunctionDeclaration(stmt) || ts.isClassDeclaration(stmt) || ts.isEnumDeclaration(stmt)) {
			if (isDefault)
				names.add('default')
			else if (stmt.name)
				names.add(stmt.name.text)
		}
	}

	return names
}

function resolveTypeAliasText(decl: ts.TypeAliasDeclaration, checker: ts.TypeChecker): string | undefined {
	const type = checker.getTypeAtLocation(decl)
	if (type.isUnion()) {
		const literals = type.types.map(t => checker.typeToString(t))
		if (literals.length > 0 && literals.every(l => l.startsWith('"') || l.startsWith('\'') || l === 'true' || l === 'false' || RE_NUMERIC_LITERAL_TEXT.test(l)))
			return literals.join(' | ')
	}
	return undefined
}

function extractFunctionSignatureInfo(decl: ts.FunctionDeclaration, checker: ts.TypeChecker): FunctionSignatureInfo {
	const signature = checker.getSignatureFromDeclaration(decl)
	const tags = signature?.getJsDocTags() ?? []
	const description = normalizeDocsText(
		ts.displayPartsToString(signature?.getDocumentationComment(checker) ?? [])
			.trim(),
	)
	return {
		description,
		params: buildParamInfoList(decl.parameters, tags, checker),
		returnType: decl.type?.getText(),
		returnsDescription: getTagByName(tags, 'returns'),
		typeParams: getTypeParamDescriptions(tags),
		remarks: getTagByName(tags, 'remarks'),
		examples: getExamples(tags),
	}
}

function extractExportInfo(sym: ts.Symbol, checker: ts.TypeChecker, pkgDir: string, isRuntimeExport: boolean): ExportInfo | null {
	const exportedSymbol = resolveExportedSymbol(sym, checker)
	const declarations = exportedSymbol.getDeclarations()
	if (!declarations?.length)
		return null

	const decl = declarations.find(entry => isOwnDeclaration(entry, pkgDir)) || declarations[0]
	if (!decl)
		return null
	if (!isOwnDeclaration(decl, pkgDir))
		return null

	const description = getSymbolDescription(exportedSymbol, checker)
	const tags = exportedSymbol.getJsDocTags(checker)
	const isInternal = hasInternalJsDocTag(tags)
	// `@internal` type-only symbols stay out of the docs, but `@internal`
	// runtime exports are part of the real export map and must be documented
	// (flagged as internal) so the page can be trusted as an export list.
	if (isInternal && !isRuntimeExport)
		return null

	const baseInfo = {
		name: sym.getName(),
		description,
		typeOnly: !isRuntimeExport,
		internal: isInternal,
		remarks: getTagByName(tags, 'remarks'),
		examples: getExamples(tags),
		defaultValue: getTagByName(tags, 'default'),
	}

	if (ts.isFunctionDeclaration(decl)) {
		const signatures = selectFunctionApiDeclarations(declarations.filter(entry => isOwnDeclaration(entry, pkgDir)))
			.map(signatureDecl => extractFunctionSignatureInfo(signatureDecl, checker))
		const primary = signatures[0]
		return {
			...baseInfo,
			description: signatures.length > 1 ? (primary?.description || description) : description,
			kind: 'function',
			// Call-style examples would be misleading for a function that is
			// only re-exported as a type: the value cannot be imported.
			examples: isRuntimeExport && signatures.length <= 1 ? baseInfo.examples : [],
			remarks: signatures.length <= 1 ? baseInfo.remarks : undefined,
			params: signatures.length <= 1 ? primary?.params : undefined,
			returnType: signatures.length <= 1 ? primary?.returnType : undefined,
			returnsDescription: signatures.length <= 1 ? primary?.returnsDescription : undefined,
			typeParams: signatures.length <= 1 ? primary?.typeParams : undefined,
			signatures: signatures.length > 1 ? signatures : undefined,
		}
	}

	if (ts.isInterfaceDeclaration(decl)) {
		return {
			...baseInfo,
			kind: 'interface',
			typeOnly: true,
			members: decl.members
				.filter(ts.isPropertySignature)
				.flatMap((member) => {
					const memberSym = member.name ? checker.getSymbolAtLocation(member.name) : undefined
					const memberTags = memberSym ? memberSym.getJsDocTags(checker) : []
					if (hasInternalJsDocTag(memberTags))
						return []
					return [{
						name: member.name?.getText() || '',
						type: member.type?.getText() || '',
						description: memberSym ? getSymbolDescription(memberSym, checker) : '',
						optional: !!member.questionToken,
						defaultValue: getTagByName(memberTags, 'default'),
					}]
				}),
			typeParams: getTypeParamDescriptions(tags),
		}
	}

	if (ts.isTypeAliasDeclaration(decl)) {
		const resolvedType = resolveTypeAliasText(decl, checker)
		return {
			...baseInfo,
			kind: 'type',
			typeOnly: true,
			resolvedType,
			typeParams: getTypeParamDescriptions(tags),
		}
	}

	if (ts.isVariableDeclaration(decl)) {
		return {
			...baseInfo,
			kind: 'const',
		}
	}

	if (ts.isClassDeclaration(decl)) {
		const classMembers: MemberInfo[] = []
		const classMethods: MethodInfo[] = []

		for (const member of decl.members) {
			if (isPrivateOrProtectedDeclaration(member))
				continue

			if (ts.isPropertyDeclaration(member) && member.name) {
				const memberSym = checker.getSymbolAtLocation(member.name)
				const memberTags = memberSym ? memberSym.getJsDocTags(checker) : []
				if (hasInternalJsDocTag(memberTags))
					continue
				classMembers.push({
					name: member.name.getText(),
					type: member.type?.getText() || '',
					description: memberSym ? getSymbolDescription(memberSym, checker) : '',
					optional: !!member.questionToken,
					defaultValue: getTagByName(memberTags, 'default'),
				})
			}
			else if (ts.isMethodDeclaration(member) && member.name) {
				const memberSym = checker.getSymbolAtLocation(member.name)
				const memberTags = memberSym ? memberSym.getJsDocTags(checker) : []
				if (hasInternalJsDocTag(memberTags))
					continue
				classMethods.push({
					name: member.name.getText(),
					description: memberSym ? getSymbolDescription(memberSym, checker) : '',
					params: buildParamInfoList(member.parameters, memberTags, checker),
					returnType: member.type?.getText(),
					returnsDescription: getTagByName(memberTags, 'returns'),
					typeParams: getTypeParamDescriptions(memberTags),
				})
			}
		}

		return {
			...baseInfo,
			kind: 'class',
			members: classMembers.length > 0 ? classMembers : undefined,
			methods: classMethods.length > 0 ? classMethods : undefined,
			typeParams: getTypeParamDescriptions(tags),
		}
	}

	if (description) {
		return {
			...baseInfo,
			kind: 'unknown',
		}
	}

	return null
}

function extractAugmentations(sourceFile: ts.SourceFile, checker: ts.TypeChecker): AugmentationInfo[] {
	const augmentations: AugmentationInfo[] = []

	for (const stmt of sourceFile.statements) {
		if (!ts.isModuleDeclaration(stmt) || !ts.isStringLiteral(stmt.name) || !stmt.body || !ts.isModuleBlock(stmt.body))
			continue

		for (const innerStmt of stmt.body.statements) {
			if (!ts.isInterfaceDeclaration(innerStmt))
				continue

			const members = innerStmt.members
				.filter(ts.isPropertySignature)
				.flatMap((member) => {
					const memberSym = member.name ? checker.getSymbolAtLocation(member.name) : undefined
					const memberTags = memberSym ? memberSym.getJsDocTags(checker) : []
					if (hasInternalJsDocTag(memberTags))
						return []
					return [{
						name: member.name?.getText() || '',
						type: member.type?.getText() || '',
						description: memberSym ? getSymbolDescription(memberSym, checker) : '',
						optional: !!member.questionToken,
						defaultValue: getTagByName(memberTags, 'default'),
					}]
				})

			if (members.length > 0) {
				augmentations.push({
					moduleName: stmt.name.text,
					interfaceName: innerStmt.name.text,
					members,
				})
			}
		}
	}

	return augmentations
}

function extractPackageAPI(pkg: PackageDef, program: ts.Program, checker: ts.TypeChecker, valueExportNamesCache: Map<string, Set<string>>): PackageAPIInfo {
	const entryPath = join(ROOT, 'packages', pkg.dir, 'src/index.ts')
	const sourceFile = program.getSourceFile(entryPath)
	if (!sourceFile) {
		console.warn(`⚠ Cannot find source file for ${pkg.name}: ${entryPath}`)
		return { pkg, exports: [], augmentations: [], relatedSources: [`packages/${pkg.dir}/src/index.ts`] }
	}

	const moduleSymbol = checker.getSymbolAtLocation(sourceFile)
	if (!moduleSymbol) {
		console.warn(`⚠ Cannot get module symbol for ${pkg.name}`)
		return { pkg, exports: [], augmentations: [], relatedSources: [`packages/${pkg.dir}/src/index.ts`] }
	}

	const exports: ExportInfo[] = []
	const relatedSourceSet = new Set<string>([`packages/${pkg.dir}/src/index.ts`])
	const valueExportNames = collectValueExportNames(sourceFile, checker, valueExportNamesCache)

	for (const sym of checker.getExportsOfModule(moduleSymbol)) {
		const info = extractExportInfo(sym, checker, pkg.dir, valueExportNames.has(sym.getName()))
		if (info)
			exports.push(info)

		for (const sourcePath of collectOwnSourcePaths(resolveExportedSymbol(sym, checker), pkg.dir))
			relatedSourceSet.add(sourcePath)
	}

	exports.sort((left, right) => {
		const order: Record<ExportInfo['kind'], number> = { function: 0, const: 1, class: 2, interface: 3, type: 4, unknown: 5 }
		return order[left.kind] - order[right.kind]
	})

	// Collect augmentations from ALL source files in this package, not just the entry file
	const pkgSourceFiles = program.getSourceFiles()
		.filter(sf =>
			sf.fileName.includes(`/packages/${pkg.dir}/src/`),
		)
	const rawAugmentations = pkgSourceFiles.flatMap(sf => extractAugmentations(sf, checker))

	// Merge augmentations that target the same module + interface to avoid duplicate heading anchors
	const augmentationMap = new Map<string, AugmentationInfo>()
	for (const aug of rawAugmentations) {
		const key = `${aug.moduleName}\0${aug.interfaceName}`
		const existing = augmentationMap.get(key)
		if (existing) {
			for (const member of aug.members) {
				if (!existing.members.some(m => m.name === member.name))
					existing.members.push(member)
			}
		}
		else {
			augmentationMap.set(key, { ...aug, members: [...aug.members] })
		}
	}
	const augmentations = [...augmentationMap.values()]

	return {
		pkg,
		exports,
		augmentations,
		relatedSources: [...relatedSourceSet].sort(),
	}
}

function escapeTable(text: string): string {
	return text
		.replace(RE_TABLE_PIPE, '\\|')
		.replace(RE_NEWLINE, ' ')
}

function slugify(text: string): string {
	return text
		.normalize('NFKD')
		.replace(RE_COMBINING_MARKS, '')
		.replace(RE_SLUG_PUNCTUATION, '-')
		.replace(RE_REPEATED_DASH, '-')
		.replace(RE_TRIM_DASH, '')
		.replace(RE_LEADING_DIGIT, '_$1')
		.toLowerCase()
}

function exportHeadingText(exp: ExportInfo): string {
	if (exp.kind !== 'function')
		return exp.name
	if (exp.signatures && exp.signatures.length > 1)
		return exp.name

	const params = exp.params
		?.map(param => (param.optional ? `${param.name}?` : param.name))
		.join(', ') || ''
	return `${exp.name}(${params})`
}

function packageRoute(pkg: PackageDef): string {
	return `/api/${pkg.slug}`
}

function packageOutputPath(pkg: PackageDef): string {
	return join(ROOT, 'docs/api', `${pkg.slug}.md`)
}

function packageGuideLink(pkg: PackageDef) {
	return pkg.guideLink ?? null
}

function neighboringPackage(packages: PackageAPIInfo[], pkg: PackageDef): PackageDef | null {
	const index = packages.findIndex(entry => entry.pkg.name === pkg.name)
	if (index === -1)
		return null

	return packages[index + 1]?.pkg ?? packages[index - 1]?.pkg ?? null
}

function exportAnchor(exp: ExportInfo): string {
	return slugify(`${exp.kind}-${exportHeadingText(exp)}`)
}

function augmentationAnchor(augmentation: AugmentationInfo): string {
	return slugify(`augmentation-${augmentation.interfaceName}-${augmentation.moduleName}`)
}

function collectCoverageGaps(info: PackageAPIInfo): CoverageGap[] {
	const gaps: CoverageGap[] = []

	for (const exp of info.exports) {
		const missing: string[] = []
		if (!exp.description)
			missing.push('summary')

		for (const param of exp.params ?? []) {
			if (!param.description)
				missing.push(`parameter ${param.name}`)
		}

		for (const [index, signature] of (exp.signatures ?? []).entries()) {
			if (!signature.description)
				missing.push(`overload ${index + 1} summary`)
			for (const param of signature.params) {
				if (!param.description)
					missing.push(`overload ${index + 1} parameter ${param.name}`)
			}
		}

		for (const member of exp.members ?? []) {
			if (!member.description)
				missing.push(`member ${member.name}`)
		}

		for (const method of exp.methods ?? []) {
			if (!method.description)
				missing.push(`method ${method.name}`)
			for (const param of method.params) {
				if (!param.description)
					missing.push(`method ${method.name} parameter ${param.name}`)
			}
		}

		if (missing.length > 0)
			gaps.push({ subject: exportHeadingText(exp), missing })
	}

	for (const augmentation of info.augmentations) {
		const missing = augmentation.members
			.filter(member => !member.description)
			.map(member => `member ${member.name}`)

		if (missing.length > 0)
			gaps.push({ subject: `${augmentation.interfaceName} (${augmentation.moduleName})`, missing })
	}

	return gaps
}

function pushExamples(lines: string[], examples?: string[]) {
	for (const example of examples ?? []) {
		lines.push(example.trim())
		lines.push('')
	}
}

function pushFunctionSignatureDetail(lines: string[], name: string, signature: FunctionSignatureInfo, index: number, localeData: Locale, inheritedDescription: string) {
	const params = signature.params
		.map(param => (param.optional ? `${param.name}?` : param.name))
		.join(', ')
	lines.push(`#### Overload ${index + 1}: \`${name}(${params})\``)
	lines.push('')
	if (signature.description && signature.description !== inheritedDescription) {
		lines.push(signature.description)
		lines.push('')
	}
	if (signature.typeParams?.length) {
		lines.push(`**${localeData.typeParams}:**`)
		lines.push('')
		for (const typeParam of signature.typeParams)
			lines.push(`- \`${typeParam.name}\` - ${typeParam.description || localeData.missingSummary}`)
		lines.push('')
	}
	if (signature.params.length > 0) {
		lines.push(`| ${localeData.paramCol} | ${localeData.typeCol} | ${localeData.descCol} |`)
		lines.push('|---|---|---|')
		for (const param of signature.params)
			lines.push(`| \`${param.name}${param.optional ? '?' : ''}\` | \`${escapeTable(param.type)}\` | ${escapeTable(param.description || localeData.missingSummary)} |`)
		lines.push('')
	}
	if (signature.returnType) {
		const returnsDescription = signature.returnsDescription ? ` - ${signature.returnsDescription}` : ''
		lines.push(`**${localeData.returns}:** \`${escapeTable(signature.returnType)}\`${returnsDescription}`)
		lines.push('')
	}
	if (signature.remarks) {
		lines.push(`**${localeData.remarks}:**`)
		lines.push('')
		lines.push(signature.remarks)
		lines.push('')
	}
	pushExamples(lines, signature.examples)
}

function pushExportDetail(lines: string[], exp: ExportInfo, localeData: Locale, pkg: PackageDef) {
	lines.push(`### ${exportHeadingText(exp)} {#${exportAnchor(exp)}}`)
	lines.push('')
	lines.push(exp.description || localeData.missingSummary)
	lines.push('')

	// Interfaces and type aliases are obviously type-only; only value-shaped
	// declarations (functions, consts, classes) need the explicit warning.
	if (exp.typeOnly && (exp.kind === 'function' || exp.kind === 'const' || exp.kind === 'class')) {
		lines.push(localeData.typeOnlyNote(pkg))
		lines.push('')
	}

	if (exp.internal) {
		lines.push(localeData.internalNote)
		lines.push('')
	}

	if (exp.signatures?.length) {
		for (const [index, signature] of exp.signatures.entries())
			pushFunctionSignatureDetail(lines, exp.name, signature, index, localeData, exp.description)
	}

	if (exp.resolvedType) {
		lines.push(`**${localeData.typeCol}:** \`${exp.resolvedType}\``)
		lines.push('')
	}

	if (exp.typeParams?.length) {
		lines.push(`**${localeData.typeParams}:**`)
		lines.push('')
		for (const typeParam of exp.typeParams)
			lines.push(`- \`${typeParam.name}\` - ${typeParam.description || localeData.missingSummary}`)
		lines.push('')
	}

	if (exp.params?.length) {
		lines.push(`| ${localeData.paramCol} | ${localeData.typeCol} | ${localeData.descCol} |`)
		lines.push('|---|---|---|')
		for (const param of exp.params)
			lines.push(`| \`${param.name}${param.optional ? '?' : ''}\` | \`${escapeTable(param.type)}\` | ${escapeTable(param.description || localeData.missingSummary)} |`)
		lines.push('')
	}

	if (exp.returnType) {
		const returnsDescription = exp.returnsDescription ? ` - ${exp.returnsDescription}` : ''
		lines.push(`**${localeData.returns}:** \`${escapeTable(exp.returnType)}\`${returnsDescription}`)
		lines.push('')
	}

	if (exp.members?.length) {
		lines.push(`| ${localeData.propertyCol} | ${localeData.typeCol} | ${localeData.descCol} | ${localeData.defaultCol} |`)
		lines.push('|---|---|---|---|')
		for (const member of exp.members) {
			const defaultValue = member.defaultValue ? `\`${escapeTable(member.defaultValue)}\`` : '—'
			lines.push(`| \`${member.name}${member.optional ? '?' : ''}\` | \`${escapeTable(member.type)}\` | ${escapeTable(member.description || localeData.missingSummary)} | ${defaultValue} |`)
		}
		lines.push('')
	}

	if (exp.methods?.length) {
		lines.push(`**${localeData.methods}:**`)
		lines.push('')
		for (const method of exp.methods) {
			const methodParams = method.params
				.map(p => (p.optional ? `${p.name}?` : p.name))
				.join(', ')
			lines.push(`#### ${method.name}(${methodParams})`)
			lines.push('')
			lines.push(method.description || localeData.missingSummary)
			lines.push('')
			if (method.typeParams?.length) {
				lines.push(`**${localeData.typeParams}:**`)
				lines.push('')
				for (const tp of method.typeParams)
					lines.push(`- \`${tp.name}\` - ${tp.description || localeData.missingSummary}`)
				lines.push('')
			}
			if (method.params.length > 0) {
				lines.push(`| ${localeData.paramCol} | ${localeData.typeCol} | ${localeData.descCol} |`)
				lines.push('|---|---|---|')
				for (const param of method.params)
					lines.push(`| \`${param.name}${param.optional ? '?' : ''}\` | \`${escapeTable(param.type)}\` | ${escapeTable(param.description || localeData.missingSummary)} |`)
				lines.push('')
			}
			if (method.returnType) {
				const returnsDesc = method.returnsDescription ? ` - ${method.returnsDescription}` : ''
				lines.push(`**${localeData.returns}:** \`${escapeTable(method.returnType)}\`${returnsDesc}`)
				lines.push('')
			}
		}
	}

	if (exp.remarks) {
		lines.push(`**${localeData.remarks}:**`)
		lines.push('')
		lines.push(exp.remarks)
		lines.push('')
	}

	pushExamples(lines, exp.examples)

	lines.push('<br>')
	lines.push('<br>')
	lines.push('')
}

function pushAugmentationDetail(lines: string[], augmentation: AugmentationInfo, localeData: Locale) {
	lines.push(`### ${augmentation.interfaceName} (${augmentation.moduleName}) {#${augmentationAnchor(augmentation)}}`)
	lines.push('')
	lines.push(`| ${localeData.propertyCol} | ${localeData.typeCol} | ${localeData.descCol} | ${localeData.defaultCol} |`)
	lines.push('|---|---|---|---|')
	for (const member of augmentation.members) {
		const defaultValue = member.defaultValue ? `\`${escapeTable(member.defaultValue)}\`` : '—'
		lines.push(`| \`${member.name}${member.optional ? '?' : ''}\` | \`${escapeTable(member.type)}\` | ${escapeTable(member.description || localeData.missingSummary)} | ${defaultValue} |`)
	}
	lines.push('')
}

function buildNextLinks(pkg: PackageDef, packages: PackageAPIInfo[]) {
	const links: Array<{ text: string, url: string }> = []
	const guideLink = packageGuideLink(pkg)
	const neighbor = neighboringPackage(packages, pkg)

	if (guideLink)
		links.push(guideLink)

	if (neighbor) {
		links.push({
			text: neighbor.pageTitle,
			url: packageRoute(neighbor),
		})
	}

	links.push(EN.overviewLink)
	return links
}

function renderPackagePage(info: PackageAPIInfo, packages: PackageAPIInfo[]): string {
	const localeData = EN
	const lines: string[] = []
	const guideLink = packageGuideLink(info.pkg)
	const reExportTarget = info.pkg.reExports ? PACKAGES.find(pkg => pkg.name === info.pkg.reExports) ?? null : null
	// Type-only exports (e.g. `export type * from ...` re-exports of plugin
	// factory functions) belong under Types regardless of declaration kind.
	const functions = info.exports.filter(exp => exp.kind === 'function' && !exp.typeOnly)
	const constants = info.exports.filter(exp => exp.kind === 'const' && !exp.typeOnly)
	const classes = info.exports.filter(exp => exp.kind === 'class' && !exp.typeOnly)
	const types = info.exports.filter(exp => exp.typeOnly || exp.kind === 'interface' || exp.kind === 'type' || exp.kind === 'unknown')

	lines.push('---')
	lines.push(`title: ${info.pkg.pageTitle}`)
	lines.push(`description: ${localeData.generatedDescription(info.pkg)}`)
	lines.push(`outline: [2, 3]`)
	lines.push('relatedPackages:')
	lines.push(`  - '${info.pkg.name}'`)
	lines.push('relatedSources:')
	for (const sourcePath of info.relatedSources)
		lines.push(`  - '${sourcePath}'`)
	lines.push('category: api')
	lines.push(`order: ${info.pkg.order}`)
	lines.push('---')
	lines.push('')
	lines.push(localeData.generatedNote)
	lines.push('')
	lines.push(`# ${info.pkg.pageTitle}`)
	lines.push('')

	const entrySource = `packages/${info.pkg.dir}/src/index.ts`
	// Collapsible meta block
	lines.push(`<details>`)
	lines.push(`<summary>${localeData.sourceInfoSummary}</summary>`)
	lines.push('')
	lines.push(`- Package: \`${info.pkg.name}\``)
	lines.push(`- ${localeData.sourceIntro} \`${entrySource}\`.`)
	lines.push(`- ${localeData.sourceFilesLabel}: ${info.relatedSources
		.map(sourcePath => `\`${sourcePath}\``)
		.join(', ')}`)
	lines.push('')
	lines.push(`</details>`)
	lines.push('')

	lines.push(`## ${localeData.packageSummary}`)
	lines.push('')
	let summary = info.pkg.description
	if (reExportTarget)
		summary += ` ${localeData.reExports} [\`${reExportTarget.name}\`](${packageRoute(reExportTarget)}).`
	else if (info.pkg.reExports)
		summary += ` ${localeData.reExports} \`${info.pkg.reExports}\`.`
	lines.push(summary)
	lines.push('')
	if (guideLink) {
		lines.push(`Use [${guideLink.text}](${guideLink.url}) when you need conceptual usage guidance instead of exact symbol lookup.`)
		lines.push('')
	}

	if (functions.length > 0) {
		lines.push(`## ${localeData.functions}`)
		lines.push('')
		for (const fn of functions.toSorted((a, b) => a.name.localeCompare(b.name)))
			pushExportDetail(lines, fn, localeData, info.pkg)
	}

	if (constants.length > 0) {
		lines.push(`## ${localeData.constants}`)
		lines.push('')
		for (const constant of constants.toSorted((a, b) => a.name.localeCompare(b.name)))
			pushExportDetail(lines, constant, localeData, info.pkg)
	}

	if (classes.length > 0) {
		lines.push(`## ${localeData.classes}`)
		lines.push('')
		for (const cls of classes.toSorted((a, b) => a.name.localeCompare(b.name)))
			pushExportDetail(lines, cls, localeData, info.pkg)
	}

	if (types.length > 0) {
		lines.push(`## ${localeData.types}`)
		lines.push('')
		for (const typeExport of types.toSorted((a, b) => a.name.localeCompare(b.name)))
			pushExportDetail(lines, typeExport, localeData, info.pkg)
	}

	if (info.augmentations.length > 0) {
		lines.push(`## ${localeData.moduleAugmentations}`)
		lines.push('')
		for (const augmentation of info.augmentations.toSorted((a, b) => a.interfaceName.localeCompare(b.interfaceName)))
			pushAugmentationDetail(lines, augmentation, localeData)
	}

	// Next section heading
	lines.push('## Next')
	lines.push('')
	for (const link of buildNextLinks(info.pkg, packages))
		lines.push(`- [${link.text}](${link.url})`)
	lines.push('')

	return lines.join('\n')
}

console.log('Creating TypeScript program...')
const program = createApiProgram()
const checker = program.getTypeChecker()

console.log('Extracting API info from packages...')
const valueExportNamesCache = new Map<string, Set<string>>()
const packages = PACKAGES.map(pkg => extractPackageAPI(pkg, program, checker, valueExportNamesCache))

for (const info of packages)
	console.log(`  ${info.pkg.name}: ${info.exports.length} exports, ${info.augmentations.length} augmentations`)

for (const info of packages) {
	writeFileSync(packageOutputPath(info.pkg), renderPackagePage(info, packages))
	console.log(`  wrote docs/api/${info.pkg.slug}.md`)
}

// Report JSDoc coverage gaps to stdout
const allGaps = packages.flatMap((info) => {
	const gaps = collectCoverageGaps(info)
	return gaps.map(gap => ({ pkg: info.pkg.name, ...gap }))
})
if (allGaps.length > 0) {
	console.log('')
	console.log('⚠ JSDoc coverage gaps:')
	for (const gap of allGaps)
		console.log(`  ${gap.pkg} → ${gap.subject}: ${gap.missing.join(', ')}`)
	process.exitCode = 1
}
else {
	console.log('')
	console.log('✅ No JSDoc coverage gaps detected.')
}

console.log('✅ Package-level API reference docs generated')
console.log('   Overview page remains hand-authored: docs/api/index.md')
